"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AtualizarPerfilFMInput = void 0;
var graphql_1 = require("@nestjs/graphql");
var AtualizarPerfilFMInput = function () {
    var _classDecorators = [(0, graphql_1.InputType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _jogadorId_decorators;
    var _jogadorId_initializers = [];
    var _jogadorId_extraInitializers = [];
    var _cabeceamento_decorators;
    var _cabeceamento_initializers = [];
    var _cabeceamento_extraInitializers = [];
    var _chutesLonge_decorators;
    var _chutesLonge_initializers = [];
    var _chutesLonge_extraInitializers = [];
    var _cobrancaFalta_decorators;
    var _cobrancaFalta_initializers = [];
    var _cobrancaFalta_extraInitializers = [];
    var _cruzamento_decorators;
    var _cruzamento_initializers = [];
    var _cruzamento_extraInitializers = [];
    var _desarme_decorators;
    var _desarme_initializers = [];
    var _desarme_extraInitializers = [];
    var _drible_decorators;
    var _drible_initializers = [];
    var _drible_extraInitializers = [];
    var _escanteios_decorators;
    var _escanteios_initializers = [];
    var _escanteios_extraInitializers = [];
    var _finalizacao_decorators;
    var _finalizacao_initializers = [];
    var _finalizacao_extraInitializers = [];
    var _laterais_decorators;
    var _laterais_initializers = [];
    var _laterais_extraInitializers = [];
    var _marcacao_decorators;
    var _marcacao_initializers = [];
    var _marcacao_extraInitializers = [];
    var _passe_decorators;
    var _passe_initializers = [];
    var _passe_extraInitializers = [];
    var _penaltis_decorators;
    var _penaltis_initializers = [];
    var _penaltis_extraInitializers = [];
    var _primeiroToque_decorators;
    var _primeiroToque_initializers = [];
    var _primeiroToque_extraInitializers = [];
    var _tecnica_decorators;
    var _tecnica_initializers = [];
    var _tecnica_extraInitializers = [];
    var _agressividade_decorators;
    var _agressividade_initializers = [];
    var _agressividade_extraInitializers = [];
    var _antecipacao_decorators;
    var _antecipacao_initializers = [];
    var _antecipacao_extraInitializers = [];
    var _bravura_decorators;
    var _bravura_initializers = [];
    var _bravura_extraInitializers = [];
    var _compostura_decorators;
    var _compostura_initializers = [];
    var _compostura_extraInitializers = [];
    var _concentracao_decorators;
    var _concentracao_initializers = [];
    var _concentracao_extraInitializers = [];
    var _decisoes_decorators;
    var _decisoes_initializers = [];
    var _decisoes_extraInitializers = [];
    var _determinacao_decorators;
    var _determinacao_initializers = [];
    var _determinacao_extraInitializers = [];
    var _imprevisibilidade_decorators;
    var _imprevisibilidade_initializers = [];
    var _imprevisibilidade_extraInitializers = [];
    var _indiceTrabalho_decorators;
    var _indiceTrabalho_initializers = [];
    var _indiceTrabalho_extraInitializers = [];
    var _lideranca_decorators;
    var _lideranca_initializers = [];
    var _lideranca_extraInitializers = [];
    var _posicionamento_decorators;
    var _posicionamento_initializers = [];
    var _posicionamento_extraInitializers = [];
    var _semBola_decorators;
    var _semBola_initializers = [];
    var _semBola_extraInitializers = [];
    var _trabalhoEquipe_decorators;
    var _trabalhoEquipe_initializers = [];
    var _trabalhoEquipe_extraInitializers = [];
    var _visaoJogo_decorators;
    var _visaoJogo_initializers = [];
    var _visaoJogo_extraInitializers = [];
    var _aceleracao_decorators;
    var _aceleracao_initializers = [];
    var _aceleracao_extraInitializers = [];
    var _agilidade_decorators;
    var _agilidade_initializers = [];
    var _agilidade_extraInitializers = [];
    var _aptidaoNatural_decorators;
    var _aptidaoNatural_initializers = [];
    var _aptidaoNatural_extraInitializers = [];
    var _equilibrio_decorators;
    var _equilibrio_initializers = [];
    var _equilibrio_extraInitializers = [];
    var _forca_decorators;
    var _forca_initializers = [];
    var _forca_extraInitializers = [];
    var _impulsao_decorators;
    var _impulsao_initializers = [];
    var _impulsao_extraInitializers = [];
    var _resistencia_decorators;
    var _resistencia_initializers = [];
    var _resistencia_extraInitializers = [];
    var _velocidade_decorators;
    var _velocidade_initializers = [];
    var _velocidade_extraInitializers = [];
    var _alcanceAereo_decorators;
    var _alcanceAereo_initializers = [];
    var _alcanceAereo_extraInitializers = [];
    var _comandoArea_decorators;
    var _comandoArea_initializers = [];
    var _comandoArea_extraInitializers = [];
    var _comunicacao_decorators;
    var _comunicacao_initializers = [];
    var _comunicacao_extraInitializers = [];
    var _excentricidade_decorators;
    var _excentricidade_initializers = [];
    var _excentricidade_extraInitializers = [];
    var _jogoMaos_decorators;
    var _jogoMaos_initializers = [];
    var _jogoMaos_extraInitializers = [];
    var _lancamentos_decorators;
    var _lancamentos_initializers = [];
    var _lancamentos_extraInitializers = [];
    var _reflexos_decorators;
    var _reflexos_initializers = [];
    var _reflexos_extraInitializers = [];
    var _reposicao_decorators;
    var _reposicao_initializers = [];
    var _reposicao_extraInitializers = [];
    var _saidaGol_decorators;
    var _saidaGol_initializers = [];
    var _saidaGol_extraInitializers = [];
    var _socos_decorators;
    var _socos_initializers = [];
    var _socos_extraInitializers = [];
    var _umContraUm_decorators;
    var _umContraUm_initializers = [];
    var _umContraUm_extraInitializers = [];
    var AtualizarPerfilFMInput = _classThis = /** @class */ (function () {
        function AtualizarPerfilFMInput_1() {
            this.jogadorId = __runInitializers(this, _jogadorId_initializers, void 0);
            // Técnicos
            this.cabeceamento = (__runInitializers(this, _jogadorId_extraInitializers), __runInitializers(this, _cabeceamento_initializers, void 0));
            this.chutesLonge = (__runInitializers(this, _cabeceamento_extraInitializers), __runInitializers(this, _chutesLonge_initializers, void 0));
            this.cobrancaFalta = (__runInitializers(this, _chutesLonge_extraInitializers), __runInitializers(this, _cobrancaFalta_initializers, void 0));
            this.cruzamento = (__runInitializers(this, _cobrancaFalta_extraInitializers), __runInitializers(this, _cruzamento_initializers, void 0));
            this.desarme = (__runInitializers(this, _cruzamento_extraInitializers), __runInitializers(this, _desarme_initializers, void 0));
            this.drible = (__runInitializers(this, _desarme_extraInitializers), __runInitializers(this, _drible_initializers, void 0));
            this.escanteios = (__runInitializers(this, _drible_extraInitializers), __runInitializers(this, _escanteios_initializers, void 0));
            this.finalizacao = (__runInitializers(this, _escanteios_extraInitializers), __runInitializers(this, _finalizacao_initializers, void 0));
            this.laterais = (__runInitializers(this, _finalizacao_extraInitializers), __runInitializers(this, _laterais_initializers, void 0));
            this.marcacao = (__runInitializers(this, _laterais_extraInitializers), __runInitializers(this, _marcacao_initializers, void 0));
            this.passe = (__runInitializers(this, _marcacao_extraInitializers), __runInitializers(this, _passe_initializers, void 0));
            this.penaltis = (__runInitializers(this, _passe_extraInitializers), __runInitializers(this, _penaltis_initializers, void 0));
            this.primeiroToque = (__runInitializers(this, _penaltis_extraInitializers), __runInitializers(this, _primeiroToque_initializers, void 0));
            this.tecnica = (__runInitializers(this, _primeiroToque_extraInitializers), __runInitializers(this, _tecnica_initializers, void 0));
            // Mentais
            this.agressividade = (__runInitializers(this, _tecnica_extraInitializers), __runInitializers(this, _agressividade_initializers, void 0));
            this.antecipacao = (__runInitializers(this, _agressividade_extraInitializers), __runInitializers(this, _antecipacao_initializers, void 0));
            this.bravura = (__runInitializers(this, _antecipacao_extraInitializers), __runInitializers(this, _bravura_initializers, void 0));
            this.compostura = (__runInitializers(this, _bravura_extraInitializers), __runInitializers(this, _compostura_initializers, void 0));
            this.concentracao = (__runInitializers(this, _compostura_extraInitializers), __runInitializers(this, _concentracao_initializers, void 0));
            this.decisoes = (__runInitializers(this, _concentracao_extraInitializers), __runInitializers(this, _decisoes_initializers, void 0));
            this.determinacao = (__runInitializers(this, _decisoes_extraInitializers), __runInitializers(this, _determinacao_initializers, void 0));
            this.imprevisibilidade = (__runInitializers(this, _determinacao_extraInitializers), __runInitializers(this, _imprevisibilidade_initializers, void 0));
            this.indiceTrabalho = (__runInitializers(this, _imprevisibilidade_extraInitializers), __runInitializers(this, _indiceTrabalho_initializers, void 0));
            this.lideranca = (__runInitializers(this, _indiceTrabalho_extraInitializers), __runInitializers(this, _lideranca_initializers, void 0));
            this.posicionamento = (__runInitializers(this, _lideranca_extraInitializers), __runInitializers(this, _posicionamento_initializers, void 0));
            this.semBola = (__runInitializers(this, _posicionamento_extraInitializers), __runInitializers(this, _semBola_initializers, void 0));
            this.trabalhoEquipe = (__runInitializers(this, _semBola_extraInitializers), __runInitializers(this, _trabalhoEquipe_initializers, void 0));
            this.visaoJogo = (__runInitializers(this, _trabalhoEquipe_extraInitializers), __runInitializers(this, _visaoJogo_initializers, void 0));
            // Físicos
            this.aceleracao = (__runInitializers(this, _visaoJogo_extraInitializers), __runInitializers(this, _aceleracao_initializers, void 0));
            this.agilidade = (__runInitializers(this, _aceleracao_extraInitializers), __runInitializers(this, _agilidade_initializers, void 0));
            this.aptidaoNatural = (__runInitializers(this, _agilidade_extraInitializers), __runInitializers(this, _aptidaoNatural_initializers, void 0));
            this.equilibrio = (__runInitializers(this, _aptidaoNatural_extraInitializers), __runInitializers(this, _equilibrio_initializers, void 0));
            this.forca = (__runInitializers(this, _equilibrio_extraInitializers), __runInitializers(this, _forca_initializers, void 0));
            this.impulsao = (__runInitializers(this, _forca_extraInitializers), __runInitializers(this, _impulsao_initializers, void 0));
            this.resistencia = (__runInitializers(this, _impulsao_extraInitializers), __runInitializers(this, _resistencia_initializers, void 0));
            this.velocidade = (__runInitializers(this, _resistencia_extraInitializers), __runInitializers(this, _velocidade_initializers, void 0));
            // Goleiro
            this.alcanceAereo = (__runInitializers(this, _velocidade_extraInitializers), __runInitializers(this, _alcanceAereo_initializers, void 0));
            this.comandoArea = (__runInitializers(this, _alcanceAereo_extraInitializers), __runInitializers(this, _comandoArea_initializers, void 0));
            this.comunicacao = (__runInitializers(this, _comandoArea_extraInitializers), __runInitializers(this, _comunicacao_initializers, void 0));
            this.excentricidade = (__runInitializers(this, _comunicacao_extraInitializers), __runInitializers(this, _excentricidade_initializers, void 0));
            this.jogoMaos = (__runInitializers(this, _excentricidade_extraInitializers), __runInitializers(this, _jogoMaos_initializers, void 0));
            this.lancamentos = (__runInitializers(this, _jogoMaos_extraInitializers), __runInitializers(this, _lancamentos_initializers, void 0));
            this.reflexos = (__runInitializers(this, _lancamentos_extraInitializers), __runInitializers(this, _reflexos_initializers, void 0));
            this.reposicao = (__runInitializers(this, _reflexos_extraInitializers), __runInitializers(this, _reposicao_initializers, void 0));
            this.saidaGol = (__runInitializers(this, _reposicao_extraInitializers), __runInitializers(this, _saidaGol_initializers, void 0));
            this.socos = (__runInitializers(this, _saidaGol_extraInitializers), __runInitializers(this, _socos_initializers, void 0));
            this.umContraUm = (__runInitializers(this, _socos_extraInitializers), __runInitializers(this, _umContraUm_initializers, void 0));
            __runInitializers(this, _umContraUm_extraInitializers);
        }
        return AtualizarPerfilFMInput_1;
    }());
    __setFunctionName(_classThis, "AtualizarPerfilFMInput");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _jogadorId_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _cabeceamento_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _chutesLonge_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _cobrancaFalta_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _cruzamento_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _desarme_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _drible_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _escanteios_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _finalizacao_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _laterais_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _marcacao_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _passe_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _penaltis_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _primeiroToque_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _tecnica_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _agressividade_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _antecipacao_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _bravura_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _compostura_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _concentracao_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _decisoes_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _determinacao_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _imprevisibilidade_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _indiceTrabalho_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _lideranca_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _posicionamento_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _semBola_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _trabalhoEquipe_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _visaoJogo_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _aceleracao_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _agilidade_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _aptidaoNatural_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _equilibrio_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _forca_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _impulsao_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _resistencia_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _velocidade_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _alcanceAereo_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _comandoArea_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _comunicacao_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _excentricidade_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _jogoMaos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _lancamentos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _reflexos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _reposicao_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _saidaGol_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _socos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _umContraUm_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        __esDecorate(null, null, _jogadorId_decorators, { kind: "field", name: "jogadorId", static: false, private: false, access: { has: function (obj) { return "jogadorId" in obj; }, get: function (obj) { return obj.jogadorId; }, set: function (obj, value) { obj.jogadorId = value; } }, metadata: _metadata }, _jogadorId_initializers, _jogadorId_extraInitializers);
        __esDecorate(null, null, _cabeceamento_decorators, { kind: "field", name: "cabeceamento", static: false, private: false, access: { has: function (obj) { return "cabeceamento" in obj; }, get: function (obj) { return obj.cabeceamento; }, set: function (obj, value) { obj.cabeceamento = value; } }, metadata: _metadata }, _cabeceamento_initializers, _cabeceamento_extraInitializers);
        __esDecorate(null, null, _chutesLonge_decorators, { kind: "field", name: "chutesLonge", static: false, private: false, access: { has: function (obj) { return "chutesLonge" in obj; }, get: function (obj) { return obj.chutesLonge; }, set: function (obj, value) { obj.chutesLonge = value; } }, metadata: _metadata }, _chutesLonge_initializers, _chutesLonge_extraInitializers);
        __esDecorate(null, null, _cobrancaFalta_decorators, { kind: "field", name: "cobrancaFalta", static: false, private: false, access: { has: function (obj) { return "cobrancaFalta" in obj; }, get: function (obj) { return obj.cobrancaFalta; }, set: function (obj, value) { obj.cobrancaFalta = value; } }, metadata: _metadata }, _cobrancaFalta_initializers, _cobrancaFalta_extraInitializers);
        __esDecorate(null, null, _cruzamento_decorators, { kind: "field", name: "cruzamento", static: false, private: false, access: { has: function (obj) { return "cruzamento" in obj; }, get: function (obj) { return obj.cruzamento; }, set: function (obj, value) { obj.cruzamento = value; } }, metadata: _metadata }, _cruzamento_initializers, _cruzamento_extraInitializers);
        __esDecorate(null, null, _desarme_decorators, { kind: "field", name: "desarme", static: false, private: false, access: { has: function (obj) { return "desarme" in obj; }, get: function (obj) { return obj.desarme; }, set: function (obj, value) { obj.desarme = value; } }, metadata: _metadata }, _desarme_initializers, _desarme_extraInitializers);
        __esDecorate(null, null, _drible_decorators, { kind: "field", name: "drible", static: false, private: false, access: { has: function (obj) { return "drible" in obj; }, get: function (obj) { return obj.drible; }, set: function (obj, value) { obj.drible = value; } }, metadata: _metadata }, _drible_initializers, _drible_extraInitializers);
        __esDecorate(null, null, _escanteios_decorators, { kind: "field", name: "escanteios", static: false, private: false, access: { has: function (obj) { return "escanteios" in obj; }, get: function (obj) { return obj.escanteios; }, set: function (obj, value) { obj.escanteios = value; } }, metadata: _metadata }, _escanteios_initializers, _escanteios_extraInitializers);
        __esDecorate(null, null, _finalizacao_decorators, { kind: "field", name: "finalizacao", static: false, private: false, access: { has: function (obj) { return "finalizacao" in obj; }, get: function (obj) { return obj.finalizacao; }, set: function (obj, value) { obj.finalizacao = value; } }, metadata: _metadata }, _finalizacao_initializers, _finalizacao_extraInitializers);
        __esDecorate(null, null, _laterais_decorators, { kind: "field", name: "laterais", static: false, private: false, access: { has: function (obj) { return "laterais" in obj; }, get: function (obj) { return obj.laterais; }, set: function (obj, value) { obj.laterais = value; } }, metadata: _metadata }, _laterais_initializers, _laterais_extraInitializers);
        __esDecorate(null, null, _marcacao_decorators, { kind: "field", name: "marcacao", static: false, private: false, access: { has: function (obj) { return "marcacao" in obj; }, get: function (obj) { return obj.marcacao; }, set: function (obj, value) { obj.marcacao = value; } }, metadata: _metadata }, _marcacao_initializers, _marcacao_extraInitializers);
        __esDecorate(null, null, _passe_decorators, { kind: "field", name: "passe", static: false, private: false, access: { has: function (obj) { return "passe" in obj; }, get: function (obj) { return obj.passe; }, set: function (obj, value) { obj.passe = value; } }, metadata: _metadata }, _passe_initializers, _passe_extraInitializers);
        __esDecorate(null, null, _penaltis_decorators, { kind: "field", name: "penaltis", static: false, private: false, access: { has: function (obj) { return "penaltis" in obj; }, get: function (obj) { return obj.penaltis; }, set: function (obj, value) { obj.penaltis = value; } }, metadata: _metadata }, _penaltis_initializers, _penaltis_extraInitializers);
        __esDecorate(null, null, _primeiroToque_decorators, { kind: "field", name: "primeiroToque", static: false, private: false, access: { has: function (obj) { return "primeiroToque" in obj; }, get: function (obj) { return obj.primeiroToque; }, set: function (obj, value) { obj.primeiroToque = value; } }, metadata: _metadata }, _primeiroToque_initializers, _primeiroToque_extraInitializers);
        __esDecorate(null, null, _tecnica_decorators, { kind: "field", name: "tecnica", static: false, private: false, access: { has: function (obj) { return "tecnica" in obj; }, get: function (obj) { return obj.tecnica; }, set: function (obj, value) { obj.tecnica = value; } }, metadata: _metadata }, _tecnica_initializers, _tecnica_extraInitializers);
        __esDecorate(null, null, _agressividade_decorators, { kind: "field", name: "agressividade", static: false, private: false, access: { has: function (obj) { return "agressividade" in obj; }, get: function (obj) { return obj.agressividade; }, set: function (obj, value) { obj.agressividade = value; } }, metadata: _metadata }, _agressividade_initializers, _agressividade_extraInitializers);
        __esDecorate(null, null, _antecipacao_decorators, { kind: "field", name: "antecipacao", static: false, private: false, access: { has: function (obj) { return "antecipacao" in obj; }, get: function (obj) { return obj.antecipacao; }, set: function (obj, value) { obj.antecipacao = value; } }, metadata: _metadata }, _antecipacao_initializers, _antecipacao_extraInitializers);
        __esDecorate(null, null, _bravura_decorators, { kind: "field", name: "bravura", static: false, private: false, access: { has: function (obj) { return "bravura" in obj; }, get: function (obj) { return obj.bravura; }, set: function (obj, value) { obj.bravura = value; } }, metadata: _metadata }, _bravura_initializers, _bravura_extraInitializers);
        __esDecorate(null, null, _compostura_decorators, { kind: "field", name: "compostura", static: false, private: false, access: { has: function (obj) { return "compostura" in obj; }, get: function (obj) { return obj.compostura; }, set: function (obj, value) { obj.compostura = value; } }, metadata: _metadata }, _compostura_initializers, _compostura_extraInitializers);
        __esDecorate(null, null, _concentracao_decorators, { kind: "field", name: "concentracao", static: false, private: false, access: { has: function (obj) { return "concentracao" in obj; }, get: function (obj) { return obj.concentracao; }, set: function (obj, value) { obj.concentracao = value; } }, metadata: _metadata }, _concentracao_initializers, _concentracao_extraInitializers);
        __esDecorate(null, null, _decisoes_decorators, { kind: "field", name: "decisoes", static: false, private: false, access: { has: function (obj) { return "decisoes" in obj; }, get: function (obj) { return obj.decisoes; }, set: function (obj, value) { obj.decisoes = value; } }, metadata: _metadata }, _decisoes_initializers, _decisoes_extraInitializers);
        __esDecorate(null, null, _determinacao_decorators, { kind: "field", name: "determinacao", static: false, private: false, access: { has: function (obj) { return "determinacao" in obj; }, get: function (obj) { return obj.determinacao; }, set: function (obj, value) { obj.determinacao = value; } }, metadata: _metadata }, _determinacao_initializers, _determinacao_extraInitializers);
        __esDecorate(null, null, _imprevisibilidade_decorators, { kind: "field", name: "imprevisibilidade", static: false, private: false, access: { has: function (obj) { return "imprevisibilidade" in obj; }, get: function (obj) { return obj.imprevisibilidade; }, set: function (obj, value) { obj.imprevisibilidade = value; } }, metadata: _metadata }, _imprevisibilidade_initializers, _imprevisibilidade_extraInitializers);
        __esDecorate(null, null, _indiceTrabalho_decorators, { kind: "field", name: "indiceTrabalho", static: false, private: false, access: { has: function (obj) { return "indiceTrabalho" in obj; }, get: function (obj) { return obj.indiceTrabalho; }, set: function (obj, value) { obj.indiceTrabalho = value; } }, metadata: _metadata }, _indiceTrabalho_initializers, _indiceTrabalho_extraInitializers);
        __esDecorate(null, null, _lideranca_decorators, { kind: "field", name: "lideranca", static: false, private: false, access: { has: function (obj) { return "lideranca" in obj; }, get: function (obj) { return obj.lideranca; }, set: function (obj, value) { obj.lideranca = value; } }, metadata: _metadata }, _lideranca_initializers, _lideranca_extraInitializers);
        __esDecorate(null, null, _posicionamento_decorators, { kind: "field", name: "posicionamento", static: false, private: false, access: { has: function (obj) { return "posicionamento" in obj; }, get: function (obj) { return obj.posicionamento; }, set: function (obj, value) { obj.posicionamento = value; } }, metadata: _metadata }, _posicionamento_initializers, _posicionamento_extraInitializers);
        __esDecorate(null, null, _semBola_decorators, { kind: "field", name: "semBola", static: false, private: false, access: { has: function (obj) { return "semBola" in obj; }, get: function (obj) { return obj.semBola; }, set: function (obj, value) { obj.semBola = value; } }, metadata: _metadata }, _semBola_initializers, _semBola_extraInitializers);
        __esDecorate(null, null, _trabalhoEquipe_decorators, { kind: "field", name: "trabalhoEquipe", static: false, private: false, access: { has: function (obj) { return "trabalhoEquipe" in obj; }, get: function (obj) { return obj.trabalhoEquipe; }, set: function (obj, value) { obj.trabalhoEquipe = value; } }, metadata: _metadata }, _trabalhoEquipe_initializers, _trabalhoEquipe_extraInitializers);
        __esDecorate(null, null, _visaoJogo_decorators, { kind: "field", name: "visaoJogo", static: false, private: false, access: { has: function (obj) { return "visaoJogo" in obj; }, get: function (obj) { return obj.visaoJogo; }, set: function (obj, value) { obj.visaoJogo = value; } }, metadata: _metadata }, _visaoJogo_initializers, _visaoJogo_extraInitializers);
        __esDecorate(null, null, _aceleracao_decorators, { kind: "field", name: "aceleracao", static: false, private: false, access: { has: function (obj) { return "aceleracao" in obj; }, get: function (obj) { return obj.aceleracao; }, set: function (obj, value) { obj.aceleracao = value; } }, metadata: _metadata }, _aceleracao_initializers, _aceleracao_extraInitializers);
        __esDecorate(null, null, _agilidade_decorators, { kind: "field", name: "agilidade", static: false, private: false, access: { has: function (obj) { return "agilidade" in obj; }, get: function (obj) { return obj.agilidade; }, set: function (obj, value) { obj.agilidade = value; } }, metadata: _metadata }, _agilidade_initializers, _agilidade_extraInitializers);
        __esDecorate(null, null, _aptidaoNatural_decorators, { kind: "field", name: "aptidaoNatural", static: false, private: false, access: { has: function (obj) { return "aptidaoNatural" in obj; }, get: function (obj) { return obj.aptidaoNatural; }, set: function (obj, value) { obj.aptidaoNatural = value; } }, metadata: _metadata }, _aptidaoNatural_initializers, _aptidaoNatural_extraInitializers);
        __esDecorate(null, null, _equilibrio_decorators, { kind: "field", name: "equilibrio", static: false, private: false, access: { has: function (obj) { return "equilibrio" in obj; }, get: function (obj) { return obj.equilibrio; }, set: function (obj, value) { obj.equilibrio = value; } }, metadata: _metadata }, _equilibrio_initializers, _equilibrio_extraInitializers);
        __esDecorate(null, null, _forca_decorators, { kind: "field", name: "forca", static: false, private: false, access: { has: function (obj) { return "forca" in obj; }, get: function (obj) { return obj.forca; }, set: function (obj, value) { obj.forca = value; } }, metadata: _metadata }, _forca_initializers, _forca_extraInitializers);
        __esDecorate(null, null, _impulsao_decorators, { kind: "field", name: "impulsao", static: false, private: false, access: { has: function (obj) { return "impulsao" in obj; }, get: function (obj) { return obj.impulsao; }, set: function (obj, value) { obj.impulsao = value; } }, metadata: _metadata }, _impulsao_initializers, _impulsao_extraInitializers);
        __esDecorate(null, null, _resistencia_decorators, { kind: "field", name: "resistencia", static: false, private: false, access: { has: function (obj) { return "resistencia" in obj; }, get: function (obj) { return obj.resistencia; }, set: function (obj, value) { obj.resistencia = value; } }, metadata: _metadata }, _resistencia_initializers, _resistencia_extraInitializers);
        __esDecorate(null, null, _velocidade_decorators, { kind: "field", name: "velocidade", static: false, private: false, access: { has: function (obj) { return "velocidade" in obj; }, get: function (obj) { return obj.velocidade; }, set: function (obj, value) { obj.velocidade = value; } }, metadata: _metadata }, _velocidade_initializers, _velocidade_extraInitializers);
        __esDecorate(null, null, _alcanceAereo_decorators, { kind: "field", name: "alcanceAereo", static: false, private: false, access: { has: function (obj) { return "alcanceAereo" in obj; }, get: function (obj) { return obj.alcanceAereo; }, set: function (obj, value) { obj.alcanceAereo = value; } }, metadata: _metadata }, _alcanceAereo_initializers, _alcanceAereo_extraInitializers);
        __esDecorate(null, null, _comandoArea_decorators, { kind: "field", name: "comandoArea", static: false, private: false, access: { has: function (obj) { return "comandoArea" in obj; }, get: function (obj) { return obj.comandoArea; }, set: function (obj, value) { obj.comandoArea = value; } }, metadata: _metadata }, _comandoArea_initializers, _comandoArea_extraInitializers);
        __esDecorate(null, null, _comunicacao_decorators, { kind: "field", name: "comunicacao", static: false, private: false, access: { has: function (obj) { return "comunicacao" in obj; }, get: function (obj) { return obj.comunicacao; }, set: function (obj, value) { obj.comunicacao = value; } }, metadata: _metadata }, _comunicacao_initializers, _comunicacao_extraInitializers);
        __esDecorate(null, null, _excentricidade_decorators, { kind: "field", name: "excentricidade", static: false, private: false, access: { has: function (obj) { return "excentricidade" in obj; }, get: function (obj) { return obj.excentricidade; }, set: function (obj, value) { obj.excentricidade = value; } }, metadata: _metadata }, _excentricidade_initializers, _excentricidade_extraInitializers);
        __esDecorate(null, null, _jogoMaos_decorators, { kind: "field", name: "jogoMaos", static: false, private: false, access: { has: function (obj) { return "jogoMaos" in obj; }, get: function (obj) { return obj.jogoMaos; }, set: function (obj, value) { obj.jogoMaos = value; } }, metadata: _metadata }, _jogoMaos_initializers, _jogoMaos_extraInitializers);
        __esDecorate(null, null, _lancamentos_decorators, { kind: "field", name: "lancamentos", static: false, private: false, access: { has: function (obj) { return "lancamentos" in obj; }, get: function (obj) { return obj.lancamentos; }, set: function (obj, value) { obj.lancamentos = value; } }, metadata: _metadata }, _lancamentos_initializers, _lancamentos_extraInitializers);
        __esDecorate(null, null, _reflexos_decorators, { kind: "field", name: "reflexos", static: false, private: false, access: { has: function (obj) { return "reflexos" in obj; }, get: function (obj) { return obj.reflexos; }, set: function (obj, value) { obj.reflexos = value; } }, metadata: _metadata }, _reflexos_initializers, _reflexos_extraInitializers);
        __esDecorate(null, null, _reposicao_decorators, { kind: "field", name: "reposicao", static: false, private: false, access: { has: function (obj) { return "reposicao" in obj; }, get: function (obj) { return obj.reposicao; }, set: function (obj, value) { obj.reposicao = value; } }, metadata: _metadata }, _reposicao_initializers, _reposicao_extraInitializers);
        __esDecorate(null, null, _saidaGol_decorators, { kind: "field", name: "saidaGol", static: false, private: false, access: { has: function (obj) { return "saidaGol" in obj; }, get: function (obj) { return obj.saidaGol; }, set: function (obj, value) { obj.saidaGol = value; } }, metadata: _metadata }, _saidaGol_initializers, _saidaGol_extraInitializers);
        __esDecorate(null, null, _socos_decorators, { kind: "field", name: "socos", static: false, private: false, access: { has: function (obj) { return "socos" in obj; }, get: function (obj) { return obj.socos; }, set: function (obj, value) { obj.socos = value; } }, metadata: _metadata }, _socos_initializers, _socos_extraInitializers);
        __esDecorate(null, null, _umContraUm_decorators, { kind: "field", name: "umContraUm", static: false, private: false, access: { has: function (obj) { return "umContraUm" in obj; }, get: function (obj) { return obj.umContraUm; }, set: function (obj, value) { obj.umContraUm = value; } }, metadata: _metadata }, _umContraUm_initializers, _umContraUm_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        AtualizarPerfilFMInput = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return AtualizarPerfilFMInput = _classThis;
}();
exports.AtualizarPerfilFMInput = AtualizarPerfilFMInput;
