"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Jogador = void 0;
var graphql_1 = require("@nestjs/graphql");
var perfil_fm_entity_1 = require("./perfil-fm.entity");
var partida_entity_1 = require("../../partidas/entities/partida.entity");
var Jogador = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _equipeId_decorators;
    var _equipeId_initializers = [];
    var _equipeId_extraInitializers = [];
    var _nomeCompleto_decorators;
    var _nomeCompleto_initializers = [];
    var _nomeCompleto_extraInitializers = [];
    var _nomePopular_decorators;
    var _nomePopular_initializers = [];
    var _nomePopular_extraInitializers = [];
    var _nomeOriginal_decorators;
    var _nomeOriginal_initializers = [];
    var _nomeOriginal_extraInitializers = [];
    var _dataNascimento_decorators;
    var _dataNascimento_initializers = [];
    var _dataNascimento_extraInitializers = [];
    var _nacionalidade_decorators;
    var _nacionalidade_initializers = [];
    var _nacionalidade_extraInitializers = [];
    var _categoria_decorators;
    var _categoria_initializers = [];
    var _categoria_extraInitializers = [];
    var _posicao_decorators;
    var _posicao_initializers = [];
    var _posicao_extraInitializers = [];
    var _posicaoSecundaria_decorators;
    var _posicaoSecundaria_initializers = [];
    var _posicaoSecundaria_extraInitializers = [];
    var _funcoes_decorators;
    var _funcoes_initializers = [];
    var _funcoes_extraInitializers = [];
    var _numeroCamisa_decorators;
    var _numeroCamisa_initializers = [];
    var _numeroCamisa_extraInitializers = [];
    var _peDominante_decorators;
    var _peDominante_initializers = [];
    var _peDominante_extraInitializers = [];
    var _alturaCm_decorators;
    var _alturaCm_initializers = [];
    var _alturaCm_extraInitializers = [];
    var _pesoKg_decorators;
    var _pesoKg_initializers = [];
    var _pesoKg_extraInitializers = [];
    var _fotoUrl_decorators;
    var _fotoUrl_initializers = [];
    var _fotoUrl_extraInitializers = [];
    var _emprestado_decorators;
    var _emprestado_initializers = [];
    var _emprestado_extraInitializers = [];
    var _tipoContrato_decorators;
    var _tipoContrato_initializers = [];
    var _tipoContrato_extraInitializers = [];
    var _clubeEmprestimo_decorators;
    var _clubeEmprestimo_initializers = [];
    var _clubeEmprestimo_extraInitializers = [];
    var _ativo_decorators;
    var _ativo_initializers = [];
    var _ativo_extraInitializers = [];
    var _criadoEm_decorators;
    var _criadoEm_initializers = [];
    var _criadoEm_extraInitializers = [];
    var _atualizadoEm_decorators;
    var _atualizadoEm_initializers = [];
    var _atualizadoEm_extraInitializers = [];
    var _perfilFM_decorators;
    var _perfilFM_initializers = [];
    var _perfilFM_extraInitializers = [];
    var _biografia_decorators;
    var _biografia_initializers = [];
    var _biografia_extraInitializers = [];
    var _estatisticas_decorators;
    var _estatisticas_initializers = [];
    var _estatisticas_extraInitializers = [];
    var Jogador = _classThis = /** @class */ (function () {
        function Jogador_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.equipeId = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _equipeId_initializers, void 0));
            this.nomeCompleto = (__runInitializers(this, _equipeId_extraInitializers), __runInitializers(this, _nomeCompleto_initializers, void 0));
            this.nomePopular = (__runInitializers(this, _nomeCompleto_extraInitializers), __runInitializers(this, _nomePopular_initializers, void 0));
            this.nomeOriginal = (__runInitializers(this, _nomePopular_extraInitializers), __runInitializers(this, _nomeOriginal_initializers, void 0));
            this.dataNascimento = (__runInitializers(this, _nomeOriginal_extraInitializers), __runInitializers(this, _dataNascimento_initializers, void 0));
            this.nacionalidade = (__runInitializers(this, _dataNascimento_extraInitializers), __runInitializers(this, _nacionalidade_initializers, void 0));
            this.categoria = (__runInitializers(this, _nacionalidade_extraInitializers), __runInitializers(this, _categoria_initializers, void 0));
            this.posicao = (__runInitializers(this, _categoria_extraInitializers), __runInitializers(this, _posicao_initializers, void 0));
            this.posicaoSecundaria = (__runInitializers(this, _posicao_extraInitializers), __runInitializers(this, _posicaoSecundaria_initializers, void 0));
            this.funcoes = (__runInitializers(this, _posicaoSecundaria_extraInitializers), __runInitializers(this, _funcoes_initializers, void 0));
            this.numeroCamisa = (__runInitializers(this, _funcoes_extraInitializers), __runInitializers(this, _numeroCamisa_initializers, void 0));
            this.peDominante = (__runInitializers(this, _numeroCamisa_extraInitializers), __runInitializers(this, _peDominante_initializers, void 0));
            this.alturaCm = (__runInitializers(this, _peDominante_extraInitializers), __runInitializers(this, _alturaCm_initializers, void 0));
            this.pesoKg = (__runInitializers(this, _alturaCm_extraInitializers), __runInitializers(this, _pesoKg_initializers, void 0));
            this.fotoUrl = (__runInitializers(this, _pesoKg_extraInitializers), __runInitializers(this, _fotoUrl_initializers, void 0));
            this.emprestado = (__runInitializers(this, _fotoUrl_extraInitializers), __runInitializers(this, _emprestado_initializers, void 0));
            this.tipoContrato = (__runInitializers(this, _emprestado_extraInitializers), __runInitializers(this, _tipoContrato_initializers, void 0));
            this.clubeEmprestimo = (__runInitializers(this, _tipoContrato_extraInitializers), __runInitializers(this, _clubeEmprestimo_initializers, void 0));
            this.ativo = (__runInitializers(this, _clubeEmprestimo_extraInitializers), __runInitializers(this, _ativo_initializers, void 0));
            this.criadoEm = (__runInitializers(this, _ativo_extraInitializers), __runInitializers(this, _criadoEm_initializers, void 0));
            this.atualizadoEm = (__runInitializers(this, _criadoEm_extraInitializers), __runInitializers(this, _atualizadoEm_initializers, void 0));
            this.perfilFM = (__runInitializers(this, _atualizadoEm_extraInitializers), __runInitializers(this, _perfilFM_initializers, void 0));
            this.biografia = (__runInitializers(this, _perfilFM_extraInitializers), __runInitializers(this, _biografia_initializers, void 0));
            this.estatisticas = (__runInitializers(this, _biografia_extraInitializers), __runInitializers(this, _estatisticas_initializers, void 0));
            __runInitializers(this, _estatisticas_extraInitializers);
        }
        return Jogador_1;
    }());
    __setFunctionName(_classThis, "Jogador");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _equipeId_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _nomeCompleto_decorators = [(0, graphql_1.Field)()];
        _nomePopular_decorators = [(0, graphql_1.Field)()];
        _nomeOriginal_decorators = [(0, graphql_1.Field)({ nullable: true })];
        _dataNascimento_decorators = [(0, graphql_1.Field)({ nullable: true })];
        _nacionalidade_decorators = [(0, graphql_1.Field)({ nullable: true })];
        _categoria_decorators = [(0, graphql_1.Field)()];
        _posicao_decorators = [(0, graphql_1.Field)({ nullable: true })];
        _posicaoSecundaria_decorators = [(0, graphql_1.Field)({ nullable: true })];
        _funcoes_decorators = [(0, graphql_1.Field)({ nullable: true })];
        _numeroCamisa_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _peDominante_decorators = [(0, graphql_1.Field)({ nullable: true })];
        _alturaCm_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _pesoKg_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Float; }, { nullable: true })];
        _fotoUrl_decorators = [(0, graphql_1.Field)({ nullable: true })];
        _emprestado_decorators = [(0, graphql_1.Field)()];
        _tipoContrato_decorators = [(0, graphql_1.Field)()];
        _clubeEmprestimo_decorators = [(0, graphql_1.Field)({ nullable: true })];
        _ativo_decorators = [(0, graphql_1.Field)()];
        _criadoEm_decorators = [(0, graphql_1.Field)()];
        _atualizadoEm_decorators = [(0, graphql_1.Field)()];
        _perfilFM_decorators = [(0, graphql_1.Field)(function () { return perfil_fm_entity_1.PerfilFM; }, { nullable: true })];
        _biografia_decorators = [(0, graphql_1.Field)({ nullable: true })];
        _estatisticas_decorators = [(0, graphql_1.Field)(function () { return [partida_entity_1.EstatisticaJogador]; }, { nullable: true })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _equipeId_decorators, { kind: "field", name: "equipeId", static: false, private: false, access: { has: function (obj) { return "equipeId" in obj; }, get: function (obj) { return obj.equipeId; }, set: function (obj, value) { obj.equipeId = value; } }, metadata: _metadata }, _equipeId_initializers, _equipeId_extraInitializers);
        __esDecorate(null, null, _nomeCompleto_decorators, { kind: "field", name: "nomeCompleto", static: false, private: false, access: { has: function (obj) { return "nomeCompleto" in obj; }, get: function (obj) { return obj.nomeCompleto; }, set: function (obj, value) { obj.nomeCompleto = value; } }, metadata: _metadata }, _nomeCompleto_initializers, _nomeCompleto_extraInitializers);
        __esDecorate(null, null, _nomePopular_decorators, { kind: "field", name: "nomePopular", static: false, private: false, access: { has: function (obj) { return "nomePopular" in obj; }, get: function (obj) { return obj.nomePopular; }, set: function (obj, value) { obj.nomePopular = value; } }, metadata: _metadata }, _nomePopular_initializers, _nomePopular_extraInitializers);
        __esDecorate(null, null, _nomeOriginal_decorators, { kind: "field", name: "nomeOriginal", static: false, private: false, access: { has: function (obj) { return "nomeOriginal" in obj; }, get: function (obj) { return obj.nomeOriginal; }, set: function (obj, value) { obj.nomeOriginal = value; } }, metadata: _metadata }, _nomeOriginal_initializers, _nomeOriginal_extraInitializers);
        __esDecorate(null, null, _dataNascimento_decorators, { kind: "field", name: "dataNascimento", static: false, private: false, access: { has: function (obj) { return "dataNascimento" in obj; }, get: function (obj) { return obj.dataNascimento; }, set: function (obj, value) { obj.dataNascimento = value; } }, metadata: _metadata }, _dataNascimento_initializers, _dataNascimento_extraInitializers);
        __esDecorate(null, null, _nacionalidade_decorators, { kind: "field", name: "nacionalidade", static: false, private: false, access: { has: function (obj) { return "nacionalidade" in obj; }, get: function (obj) { return obj.nacionalidade; }, set: function (obj, value) { obj.nacionalidade = value; } }, metadata: _metadata }, _nacionalidade_initializers, _nacionalidade_extraInitializers);
        __esDecorate(null, null, _categoria_decorators, { kind: "field", name: "categoria", static: false, private: false, access: { has: function (obj) { return "categoria" in obj; }, get: function (obj) { return obj.categoria; }, set: function (obj, value) { obj.categoria = value; } }, metadata: _metadata }, _categoria_initializers, _categoria_extraInitializers);
        __esDecorate(null, null, _posicao_decorators, { kind: "field", name: "posicao", static: false, private: false, access: { has: function (obj) { return "posicao" in obj; }, get: function (obj) { return obj.posicao; }, set: function (obj, value) { obj.posicao = value; } }, metadata: _metadata }, _posicao_initializers, _posicao_extraInitializers);
        __esDecorate(null, null, _posicaoSecundaria_decorators, { kind: "field", name: "posicaoSecundaria", static: false, private: false, access: { has: function (obj) { return "posicaoSecundaria" in obj; }, get: function (obj) { return obj.posicaoSecundaria; }, set: function (obj, value) { obj.posicaoSecundaria = value; } }, metadata: _metadata }, _posicaoSecundaria_initializers, _posicaoSecundaria_extraInitializers);
        __esDecorate(null, null, _funcoes_decorators, { kind: "field", name: "funcoes", static: false, private: false, access: { has: function (obj) { return "funcoes" in obj; }, get: function (obj) { return obj.funcoes; }, set: function (obj, value) { obj.funcoes = value; } }, metadata: _metadata }, _funcoes_initializers, _funcoes_extraInitializers);
        __esDecorate(null, null, _numeroCamisa_decorators, { kind: "field", name: "numeroCamisa", static: false, private: false, access: { has: function (obj) { return "numeroCamisa" in obj; }, get: function (obj) { return obj.numeroCamisa; }, set: function (obj, value) { obj.numeroCamisa = value; } }, metadata: _metadata }, _numeroCamisa_initializers, _numeroCamisa_extraInitializers);
        __esDecorate(null, null, _peDominante_decorators, { kind: "field", name: "peDominante", static: false, private: false, access: { has: function (obj) { return "peDominante" in obj; }, get: function (obj) { return obj.peDominante; }, set: function (obj, value) { obj.peDominante = value; } }, metadata: _metadata }, _peDominante_initializers, _peDominante_extraInitializers);
        __esDecorate(null, null, _alturaCm_decorators, { kind: "field", name: "alturaCm", static: false, private: false, access: { has: function (obj) { return "alturaCm" in obj; }, get: function (obj) { return obj.alturaCm; }, set: function (obj, value) { obj.alturaCm = value; } }, metadata: _metadata }, _alturaCm_initializers, _alturaCm_extraInitializers);
        __esDecorate(null, null, _pesoKg_decorators, { kind: "field", name: "pesoKg", static: false, private: false, access: { has: function (obj) { return "pesoKg" in obj; }, get: function (obj) { return obj.pesoKg; }, set: function (obj, value) { obj.pesoKg = value; } }, metadata: _metadata }, _pesoKg_initializers, _pesoKg_extraInitializers);
        __esDecorate(null, null, _fotoUrl_decorators, { kind: "field", name: "fotoUrl", static: false, private: false, access: { has: function (obj) { return "fotoUrl" in obj; }, get: function (obj) { return obj.fotoUrl; }, set: function (obj, value) { obj.fotoUrl = value; } }, metadata: _metadata }, _fotoUrl_initializers, _fotoUrl_extraInitializers);
        __esDecorate(null, null, _emprestado_decorators, { kind: "field", name: "emprestado", static: false, private: false, access: { has: function (obj) { return "emprestado" in obj; }, get: function (obj) { return obj.emprestado; }, set: function (obj, value) { obj.emprestado = value; } }, metadata: _metadata }, _emprestado_initializers, _emprestado_extraInitializers);
        __esDecorate(null, null, _tipoContrato_decorators, { kind: "field", name: "tipoContrato", static: false, private: false, access: { has: function (obj) { return "tipoContrato" in obj; }, get: function (obj) { return obj.tipoContrato; }, set: function (obj, value) { obj.tipoContrato = value; } }, metadata: _metadata }, _tipoContrato_initializers, _tipoContrato_extraInitializers);
        __esDecorate(null, null, _clubeEmprestimo_decorators, { kind: "field", name: "clubeEmprestimo", static: false, private: false, access: { has: function (obj) { return "clubeEmprestimo" in obj; }, get: function (obj) { return obj.clubeEmprestimo; }, set: function (obj, value) { obj.clubeEmprestimo = value; } }, metadata: _metadata }, _clubeEmprestimo_initializers, _clubeEmprestimo_extraInitializers);
        __esDecorate(null, null, _ativo_decorators, { kind: "field", name: "ativo", static: false, private: false, access: { has: function (obj) { return "ativo" in obj; }, get: function (obj) { return obj.ativo; }, set: function (obj, value) { obj.ativo = value; } }, metadata: _metadata }, _ativo_initializers, _ativo_extraInitializers);
        __esDecorate(null, null, _criadoEm_decorators, { kind: "field", name: "criadoEm", static: false, private: false, access: { has: function (obj) { return "criadoEm" in obj; }, get: function (obj) { return obj.criadoEm; }, set: function (obj, value) { obj.criadoEm = value; } }, metadata: _metadata }, _criadoEm_initializers, _criadoEm_extraInitializers);
        __esDecorate(null, null, _atualizadoEm_decorators, { kind: "field", name: "atualizadoEm", static: false, private: false, access: { has: function (obj) { return "atualizadoEm" in obj; }, get: function (obj) { return obj.atualizadoEm; }, set: function (obj, value) { obj.atualizadoEm = value; } }, metadata: _metadata }, _atualizadoEm_initializers, _atualizadoEm_extraInitializers);
        __esDecorate(null, null, _perfilFM_decorators, { kind: "field", name: "perfilFM", static: false, private: false, access: { has: function (obj) { return "perfilFM" in obj; }, get: function (obj) { return obj.perfilFM; }, set: function (obj, value) { obj.perfilFM = value; } }, metadata: _metadata }, _perfilFM_initializers, _perfilFM_extraInitializers);
        __esDecorate(null, null, _biografia_decorators, { kind: "field", name: "biografia", static: false, private: false, access: { has: function (obj) { return "biografia" in obj; }, get: function (obj) { return obj.biografia; }, set: function (obj, value) { obj.biografia = value; } }, metadata: _metadata }, _biografia_initializers, _biografia_extraInitializers);
        __esDecorate(null, null, _estatisticas_decorators, { kind: "field", name: "estatisticas", static: false, private: false, access: { has: function (obj) { return "estatisticas" in obj; }, get: function (obj) { return obj.estatisticas; }, set: function (obj, value) { obj.estatisticas = value; } }, metadata: _metadata }, _estatisticas_initializers, _estatisticas_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Jogador = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Jogador = _classThis;
}();
exports.Jogador = Jogador;
