"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.EstatisticaEquipe = exports.EstatisticaJogador = exports.EventoPartida = exports.Partida = exports.JogadorSimples = exports.TreinadorSimples = exports.ArbitroSimples = exports.EstadioSimples = exports.CompeticaoSimples = exports.ClassificacaoEquipe = exports.EquipeSimples = void 0;
var graphql_1 = require("@nestjs/graphql");
// ── Entidades Auxiliares ──────────────────────────────────────────────────
var EquipeSimples = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _nome_decorators;
    var _nome_initializers = [];
    var _nome_extraInitializers = [];
    var _escudoUrl_decorators;
    var _escudoUrl_initializers = [];
    var _escudoUrl_extraInitializers = [];
    var EquipeSimples = _classThis = /** @class */ (function () {
        function EquipeSimples_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.nome = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _nome_initializers, void 0));
            this.escudoUrl = (__runInitializers(this, _nome_extraInitializers), __runInitializers(this, _escudoUrl_initializers, void 0));
            __runInitializers(this, _escudoUrl_extraInitializers);
        }
        return EquipeSimples_1;
    }());
    __setFunctionName(_classThis, "EquipeSimples");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _nome_decorators = [(0, graphql_1.Field)(function () { return String; })];
        _escudoUrl_decorators = [(0, graphql_1.Field)({ nullable: true })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _nome_decorators, { kind: "field", name: "nome", static: false, private: false, access: { has: function (obj) { return "nome" in obj; }, get: function (obj) { return obj.nome; }, set: function (obj, value) { obj.nome = value; } }, metadata: _metadata }, _nome_initializers, _nome_extraInitializers);
        __esDecorate(null, null, _escudoUrl_decorators, { kind: "field", name: "escudoUrl", static: false, private: false, access: { has: function (obj) { return "escudoUrl" in obj; }, get: function (obj) { return obj.escudoUrl; }, set: function (obj, value) { obj.escudoUrl = value; } }, metadata: _metadata }, _escudoUrl_initializers, _escudoUrl_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        EquipeSimples = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return EquipeSimples = _classThis;
}();
exports.EquipeSimples = EquipeSimples;
var ClassificacaoEquipe = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _posicao_decorators;
    var _posicao_initializers = [];
    var _posicao_extraInitializers = [];
    var _pontos_decorators;
    var _pontos_initializers = [];
    var _pontos_extraInitializers = [];
    var _jogos_decorators;
    var _jogos_initializers = [];
    var _jogos_extraInitializers = [];
    var _vitorias_decorators;
    var _vitorias_initializers = [];
    var _vitorias_extraInitializers = [];
    var _empates_decorators;
    var _empates_initializers = [];
    var _empates_extraInitializers = [];
    var _derrotas_decorators;
    var _derrotas_initializers = [];
    var _derrotas_extraInitializers = [];
    var _golsPro_decorators;
    var _golsPro_initializers = [];
    var _golsPro_extraInitializers = [];
    var _golsContra_decorators;
    var _golsContra_initializers = [];
    var _golsContra_extraInitializers = [];
    var _saldoGols_decorators;
    var _saldoGols_initializers = [];
    var _saldoGols_extraInitializers = [];
    var _equipe_decorators;
    var _equipe_initializers = [];
    var _equipe_extraInitializers = [];
    var ClassificacaoEquipe = _classThis = /** @class */ (function () {
        function ClassificacaoEquipe_1() {
            this.posicao = __runInitializers(this, _posicao_initializers, void 0);
            this.pontos = (__runInitializers(this, _posicao_extraInitializers), __runInitializers(this, _pontos_initializers, void 0));
            this.jogos = (__runInitializers(this, _pontos_extraInitializers), __runInitializers(this, _jogos_initializers, void 0));
            this.vitorias = (__runInitializers(this, _jogos_extraInitializers), __runInitializers(this, _vitorias_initializers, void 0));
            this.empates = (__runInitializers(this, _vitorias_extraInitializers), __runInitializers(this, _empates_initializers, void 0));
            this.derrotas = (__runInitializers(this, _empates_extraInitializers), __runInitializers(this, _derrotas_initializers, void 0));
            this.golsPro = (__runInitializers(this, _derrotas_extraInitializers), __runInitializers(this, _golsPro_initializers, void 0));
            this.golsContra = (__runInitializers(this, _golsPro_extraInitializers), __runInitializers(this, _golsContra_initializers, void 0));
            this.saldoGols = (__runInitializers(this, _golsContra_extraInitializers), __runInitializers(this, _saldoGols_initializers, void 0));
            this.equipe = (__runInitializers(this, _saldoGols_extraInitializers), __runInitializers(this, _equipe_initializers, void 0));
            __runInitializers(this, _equipe_extraInitializers);
        }
        return ClassificacaoEquipe_1;
    }());
    __setFunctionName(_classThis, "ClassificacaoEquipe");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _posicao_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _pontos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _jogos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _vitorias_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _empates_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _derrotas_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _golsPro_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _golsContra_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _saldoGols_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _equipe_decorators = [(0, graphql_1.Field)(function () { return EquipeSimples; })];
        __esDecorate(null, null, _posicao_decorators, { kind: "field", name: "posicao", static: false, private: false, access: { has: function (obj) { return "posicao" in obj; }, get: function (obj) { return obj.posicao; }, set: function (obj, value) { obj.posicao = value; } }, metadata: _metadata }, _posicao_initializers, _posicao_extraInitializers);
        __esDecorate(null, null, _pontos_decorators, { kind: "field", name: "pontos", static: false, private: false, access: { has: function (obj) { return "pontos" in obj; }, get: function (obj) { return obj.pontos; }, set: function (obj, value) { obj.pontos = value; } }, metadata: _metadata }, _pontos_initializers, _pontos_extraInitializers);
        __esDecorate(null, null, _jogos_decorators, { kind: "field", name: "jogos", static: false, private: false, access: { has: function (obj) { return "jogos" in obj; }, get: function (obj) { return obj.jogos; }, set: function (obj, value) { obj.jogos = value; } }, metadata: _metadata }, _jogos_initializers, _jogos_extraInitializers);
        __esDecorate(null, null, _vitorias_decorators, { kind: "field", name: "vitorias", static: false, private: false, access: { has: function (obj) { return "vitorias" in obj; }, get: function (obj) { return obj.vitorias; }, set: function (obj, value) { obj.vitorias = value; } }, metadata: _metadata }, _vitorias_initializers, _vitorias_extraInitializers);
        __esDecorate(null, null, _empates_decorators, { kind: "field", name: "empates", static: false, private: false, access: { has: function (obj) { return "empates" in obj; }, get: function (obj) { return obj.empates; }, set: function (obj, value) { obj.empates = value; } }, metadata: _metadata }, _empates_initializers, _empates_extraInitializers);
        __esDecorate(null, null, _derrotas_decorators, { kind: "field", name: "derrotas", static: false, private: false, access: { has: function (obj) { return "derrotas" in obj; }, get: function (obj) { return obj.derrotas; }, set: function (obj, value) { obj.derrotas = value; } }, metadata: _metadata }, _derrotas_initializers, _derrotas_extraInitializers);
        __esDecorate(null, null, _golsPro_decorators, { kind: "field", name: "golsPro", static: false, private: false, access: { has: function (obj) { return "golsPro" in obj; }, get: function (obj) { return obj.golsPro; }, set: function (obj, value) { obj.golsPro = value; } }, metadata: _metadata }, _golsPro_initializers, _golsPro_extraInitializers);
        __esDecorate(null, null, _golsContra_decorators, { kind: "field", name: "golsContra", static: false, private: false, access: { has: function (obj) { return "golsContra" in obj; }, get: function (obj) { return obj.golsContra; }, set: function (obj, value) { obj.golsContra = value; } }, metadata: _metadata }, _golsContra_initializers, _golsContra_extraInitializers);
        __esDecorate(null, null, _saldoGols_decorators, { kind: "field", name: "saldoGols", static: false, private: false, access: { has: function (obj) { return "saldoGols" in obj; }, get: function (obj) { return obj.saldoGols; }, set: function (obj, value) { obj.saldoGols = value; } }, metadata: _metadata }, _saldoGols_initializers, _saldoGols_extraInitializers);
        __esDecorate(null, null, _equipe_decorators, { kind: "field", name: "equipe", static: false, private: false, access: { has: function (obj) { return "equipe" in obj; }, get: function (obj) { return obj.equipe; }, set: function (obj, value) { obj.equipe = value; } }, metadata: _metadata }, _equipe_initializers, _equipe_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        ClassificacaoEquipe = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return ClassificacaoEquipe = _classThis;
}();
exports.ClassificacaoEquipe = ClassificacaoEquipe;
var CompeticaoSimples = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _nome_decorators;
    var _nome_initializers = [];
    var _nome_extraInitializers = [];
    var _classificacao_decorators;
    var _classificacao_initializers = [];
    var _classificacao_extraInitializers = [];
    var CompeticaoSimples = _classThis = /** @class */ (function () {
        function CompeticaoSimples_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.nome = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _nome_initializers, void 0));
            this.classificacao = (__runInitializers(this, _nome_extraInitializers), __runInitializers(this, _classificacao_initializers, void 0));
            __runInitializers(this, _classificacao_extraInitializers);
        }
        return CompeticaoSimples_1;
    }());
    __setFunctionName(_classThis, "CompeticaoSimples");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _nome_decorators = [(0, graphql_1.Field)(function () { return String; })];
        _classificacao_decorators = [(0, graphql_1.Field)(function () { return [ClassificacaoEquipe]; }, { nullable: true })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _nome_decorators, { kind: "field", name: "nome", static: false, private: false, access: { has: function (obj) { return "nome" in obj; }, get: function (obj) { return obj.nome; }, set: function (obj, value) { obj.nome = value; } }, metadata: _metadata }, _nome_initializers, _nome_extraInitializers);
        __esDecorate(null, null, _classificacao_decorators, { kind: "field", name: "classificacao", static: false, private: false, access: { has: function (obj) { return "classificacao" in obj; }, get: function (obj) { return obj.classificacao; }, set: function (obj, value) { obj.classificacao = value; } }, metadata: _metadata }, _classificacao_initializers, _classificacao_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        CompeticaoSimples = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return CompeticaoSimples = _classThis;
}();
exports.CompeticaoSimples = CompeticaoSimples;
var EstadioSimples = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _nome_decorators;
    var _nome_initializers = [];
    var _nome_extraInitializers = [];
    var EstadioSimples = _classThis = /** @class */ (function () {
        function EstadioSimples_1() {
            this.nome = __runInitializers(this, _nome_initializers, void 0);
            __runInitializers(this, _nome_extraInitializers);
        }
        return EstadioSimples_1;
    }());
    __setFunctionName(_classThis, "EstadioSimples");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _nome_decorators = [(0, graphql_1.Field)(function () { return String; })];
        __esDecorate(null, null, _nome_decorators, { kind: "field", name: "nome", static: false, private: false, access: { has: function (obj) { return "nome" in obj; }, get: function (obj) { return obj.nome; }, set: function (obj, value) { obj.nome = value; } }, metadata: _metadata }, _nome_initializers, _nome_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        EstadioSimples = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return EstadioSimples = _classThis;
}();
exports.EstadioSimples = EstadioSimples;
var ArbitroSimples = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _nomePopular_decorators;
    var _nomePopular_initializers = [];
    var _nomePopular_extraInitializers = [];
    var ArbitroSimples = _classThis = /** @class */ (function () {
        function ArbitroSimples_1() {
            this.nomePopular = __runInitializers(this, _nomePopular_initializers, void 0);
            __runInitializers(this, _nomePopular_extraInitializers);
        }
        return ArbitroSimples_1;
    }());
    __setFunctionName(_classThis, "ArbitroSimples");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _nomePopular_decorators = [(0, graphql_1.Field)(function () { return String; })];
        __esDecorate(null, null, _nomePopular_decorators, { kind: "field", name: "nomePopular", static: false, private: false, access: { has: function (obj) { return "nomePopular" in obj; }, get: function (obj) { return obj.nomePopular; }, set: function (obj, value) { obj.nomePopular = value; } }, metadata: _metadata }, _nomePopular_initializers, _nomePopular_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        ArbitroSimples = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return ArbitroSimples = _classThis;
}();
exports.ArbitroSimples = ArbitroSimples;
var TreinadorSimples = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _nome_decorators;
    var _nome_initializers = [];
    var _nome_extraInitializers = [];
    var TreinadorSimples = _classThis = /** @class */ (function () {
        function TreinadorSimples_1() {
            this.nome = __runInitializers(this, _nome_initializers, void 0);
            __runInitializers(this, _nome_extraInitializers);
        }
        return TreinadorSimples_1;
    }());
    __setFunctionName(_classThis, "TreinadorSimples");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _nome_decorators = [(0, graphql_1.Field)(function () { return String; })];
        __esDecorate(null, null, _nome_decorators, { kind: "field", name: "nome", static: false, private: false, access: { has: function (obj) { return "nome" in obj; }, get: function (obj) { return obj.nome; }, set: function (obj, value) { obj.nome = value; } }, metadata: _metadata }, _nome_initializers, _nome_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        TreinadorSimples = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return TreinadorSimples = _classThis;
}();
exports.TreinadorSimples = TreinadorSimples;
var JogadorSimples = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _nomePopular_decorators;
    var _nomePopular_initializers = [];
    var _nomePopular_extraInitializers = [];
    var _posicao_decorators;
    var _posicao_initializers = [];
    var _posicao_extraInitializers = [];
    var _posicaoSecundaria_decorators;
    var _posicaoSecundaria_initializers = [];
    var _posicaoSecundaria_extraInitializers = [];
    var _funcoes_decorators;
    var _funcoes_initializers = [];
    var _funcoes_extraInitializers = [];
    var _fotoUrl_decorators;
    var _fotoUrl_initializers = [];
    var _fotoUrl_extraInitializers = [];
    var _peDominante_decorators;
    var _peDominante_initializers = [];
    var _peDominante_extraInitializers = [];
    var _numeroCamisa_decorators;
    var _numeroCamisa_initializers = [];
    var _numeroCamisa_extraInitializers = [];
    var JogadorSimples = _classThis = /** @class */ (function () {
        function JogadorSimples_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.nomePopular = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _nomePopular_initializers, void 0));
            this.posicao = (__runInitializers(this, _nomePopular_extraInitializers), __runInitializers(this, _posicao_initializers, void 0));
            this.posicaoSecundaria = (__runInitializers(this, _posicao_extraInitializers), __runInitializers(this, _posicaoSecundaria_initializers, void 0));
            this.funcoes = (__runInitializers(this, _posicaoSecundaria_extraInitializers), __runInitializers(this, _funcoes_initializers, void 0));
            this.fotoUrl = (__runInitializers(this, _funcoes_extraInitializers), __runInitializers(this, _fotoUrl_initializers, void 0));
            this.peDominante = (__runInitializers(this, _fotoUrl_extraInitializers), __runInitializers(this, _peDominante_initializers, void 0));
            this.numeroCamisa = (__runInitializers(this, _peDominante_extraInitializers), __runInitializers(this, _numeroCamisa_initializers, void 0));
            __runInitializers(this, _numeroCamisa_extraInitializers);
        }
        return JogadorSimples_1;
    }());
    __setFunctionName(_classThis, "JogadorSimples");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _nomePopular_decorators = [(0, graphql_1.Field)(function () { return String; })];
        _posicao_decorators = [(0, graphql_1.Field)(function () { return String; }, { nullable: true })];
        _posicaoSecundaria_decorators = [(0, graphql_1.Field)(function () { return String; }, { nullable: true })];
        _funcoes_decorators = [(0, graphql_1.Field)(function () { return String; }, { nullable: true })];
        _fotoUrl_decorators = [(0, graphql_1.Field)(function () { return String; }, { nullable: true })];
        _peDominante_decorators = [(0, graphql_1.Field)(function () { return String; }, { nullable: true })];
        _numeroCamisa_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _nomePopular_decorators, { kind: "field", name: "nomePopular", static: false, private: false, access: { has: function (obj) { return "nomePopular" in obj; }, get: function (obj) { return obj.nomePopular; }, set: function (obj, value) { obj.nomePopular = value; } }, metadata: _metadata }, _nomePopular_initializers, _nomePopular_extraInitializers);
        __esDecorate(null, null, _posicao_decorators, { kind: "field", name: "posicao", static: false, private: false, access: { has: function (obj) { return "posicao" in obj; }, get: function (obj) { return obj.posicao; }, set: function (obj, value) { obj.posicao = value; } }, metadata: _metadata }, _posicao_initializers, _posicao_extraInitializers);
        __esDecorate(null, null, _posicaoSecundaria_decorators, { kind: "field", name: "posicaoSecundaria", static: false, private: false, access: { has: function (obj) { return "posicaoSecundaria" in obj; }, get: function (obj) { return obj.posicaoSecundaria; }, set: function (obj, value) { obj.posicaoSecundaria = value; } }, metadata: _metadata }, _posicaoSecundaria_initializers, _posicaoSecundaria_extraInitializers);
        __esDecorate(null, null, _funcoes_decorators, { kind: "field", name: "funcoes", static: false, private: false, access: { has: function (obj) { return "funcoes" in obj; }, get: function (obj) { return obj.funcoes; }, set: function (obj, value) { obj.funcoes = value; } }, metadata: _metadata }, _funcoes_initializers, _funcoes_extraInitializers);
        __esDecorate(null, null, _fotoUrl_decorators, { kind: "field", name: "fotoUrl", static: false, private: false, access: { has: function (obj) { return "fotoUrl" in obj; }, get: function (obj) { return obj.fotoUrl; }, set: function (obj, value) { obj.fotoUrl = value; } }, metadata: _metadata }, _fotoUrl_initializers, _fotoUrl_extraInitializers);
        __esDecorate(null, null, _peDominante_decorators, { kind: "field", name: "peDominante", static: false, private: false, access: { has: function (obj) { return "peDominante" in obj; }, get: function (obj) { return obj.peDominante; }, set: function (obj, value) { obj.peDominante = value; } }, metadata: _metadata }, _peDominante_initializers, _peDominante_extraInitializers);
        __esDecorate(null, null, _numeroCamisa_decorators, { kind: "field", name: "numeroCamisa", static: false, private: false, access: { has: function (obj) { return "numeroCamisa" in obj; }, get: function (obj) { return obj.numeroCamisa; }, set: function (obj, value) { obj.numeroCamisa = value; } }, metadata: _metadata }, _numeroCamisa_initializers, _numeroCamisa_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        JogadorSimples = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return JogadorSimples = _classThis;
}();
exports.JogadorSimples = JogadorSimples;
// ── Entidade Principal ────────────────────────────────────────────────────
var Partida = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _dataHora_decorators;
    var _dataHora_initializers = [];
    var _dataHora_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _golsCasa_decorators;
    var _golsCasa_initializers = [];
    var _golsCasa_extraInitializers = [];
    var _golsVisitante_decorators;
    var _golsVisitante_initializers = [];
    var _golsVisitante_extraInitializers = [];
    var _golsPenaltisCasa_decorators;
    var _golsPenaltisCasa_initializers = [];
    var _golsPenaltisCasa_extraInitializers = [];
    var _golsPenaltisVisitante_decorators;
    var _golsPenaltisVisitante_initializers = [];
    var _golsPenaltisVisitante_extraInitializers = [];
    var _competicao_decorators;
    var _competicao_initializers = [];
    var _competicao_extraInitializers = [];
    var _equipeCasa_decorators;
    var _equipeCasa_initializers = [];
    var _equipeCasa_extraInitializers = [];
    var _equipeVisitante_decorators;
    var _equipeVisitante_initializers = [];
    var _equipeVisitante_extraInitializers = [];
    var _estadio_decorators;
    var _estadio_initializers = [];
    var _estadio_extraInitializers = [];
    var _arbitro_decorators;
    var _arbitro_initializers = [];
    var _arbitro_extraInitializers = [];
    var _treinadorCasa_decorators;
    var _treinadorCasa_initializers = [];
    var _treinadorCasa_extraInitializers = [];
    var _treinadorVisitante_decorators;
    var _treinadorVisitante_initializers = [];
    var _treinadorVisitante_extraInitializers = [];
    var _estatisticasEquipes_decorators;
    var _estatisticasEquipes_initializers = [];
    var _estatisticasEquipes_extraInitializers = [];
    var _eventos_decorators;
    var _eventos_initializers = [];
    var _eventos_extraInitializers = [];
    var _estatisticasJogadores_decorators;
    var _estatisticasJogadores_initializers = [];
    var _estatisticasJogadores_extraInitializers = [];
    var Partida = _classThis = /** @class */ (function () {
        function Partida_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            // 🎯 CORRIGIDO: Retornado para Date para bater com o DateTime do Prisma
            this.dataHora = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _dataHora_initializers, void 0));
            this.status = (__runInitializers(this, _dataHora_extraInitializers), __runInitializers(this, _status_initializers, void 0));
            this.golsCasa = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _golsCasa_initializers, void 0));
            this.golsVisitante = (__runInitializers(this, _golsCasa_extraInitializers), __runInitializers(this, _golsVisitante_initializers, void 0));
            this.golsPenaltisCasa = (__runInitializers(this, _golsVisitante_extraInitializers), __runInitializers(this, _golsPenaltisCasa_initializers, void 0));
            this.golsPenaltisVisitante = (__runInitializers(this, _golsPenaltisCasa_extraInitializers), __runInitializers(this, _golsPenaltisVisitante_initializers, void 0));
            this.competicao = (__runInitializers(this, _golsPenaltisVisitante_extraInitializers), __runInitializers(this, _competicao_initializers, void 0));
            this.equipeCasa = (__runInitializers(this, _competicao_extraInitializers), __runInitializers(this, _equipeCasa_initializers, void 0));
            this.equipeVisitante = (__runInitializers(this, _equipeCasa_extraInitializers), __runInitializers(this, _equipeVisitante_initializers, void 0));
            this.estadio = (__runInitializers(this, _equipeVisitante_extraInitializers), __runInitializers(this, _estadio_initializers, void 0));
            this.arbitro = (__runInitializers(this, _estadio_extraInitializers), __runInitializers(this, _arbitro_initializers, void 0));
            this.treinadorCasa = (__runInitializers(this, _arbitro_extraInitializers), __runInitializers(this, _treinadorCasa_initializers, void 0));
            this.treinadorVisitante = (__runInitializers(this, _treinadorCasa_extraInitializers), __runInitializers(this, _treinadorVisitante_initializers, void 0));
            this.estatisticasEquipes = (__runInitializers(this, _treinadorVisitante_extraInitializers), __runInitializers(this, _estatisticasEquipes_initializers, void 0));
            this.eventos = (__runInitializers(this, _estatisticasEquipes_extraInitializers), __runInitializers(this, _eventos_initializers, void 0));
            this.estatisticasJogadores = (__runInitializers(this, _eventos_extraInitializers), __runInitializers(this, _estatisticasJogadores_initializers, void 0));
            __runInitializers(this, _estatisticasJogadores_extraInitializers);
        }
        return Partida_1;
    }());
    __setFunctionName(_classThis, "Partida");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _dataHora_decorators = [(0, graphql_1.Field)(function () { return Date; })];
        _status_decorators = [(0, graphql_1.Field)(function () { return String; })];
        _golsCasa_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _golsVisitante_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _golsPenaltisCasa_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _golsPenaltisVisitante_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _competicao_decorators = [(0, graphql_1.Field)(function () { return CompeticaoSimples; })];
        _equipeCasa_decorators = [(0, graphql_1.Field)(function () { return EquipeSimples; })];
        _equipeVisitante_decorators = [(0, graphql_1.Field)(function () { return EquipeSimples; })];
        _estadio_decorators = [(0, graphql_1.Field)(function () { return EstadioSimples; }, { nullable: true })];
        _arbitro_decorators = [(0, graphql_1.Field)(function () { return ArbitroSimples; }, { nullable: true })];
        _treinadorCasa_decorators = [(0, graphql_1.Field)(function () { return TreinadorSimples; }, { nullable: true })];
        _treinadorVisitante_decorators = [(0, graphql_1.Field)(function () { return TreinadorSimples; }, { nullable: true })];
        _estatisticasEquipes_decorators = [(0, graphql_1.Field)(function () { return [EstatisticaEquipe]; }, { nullable: true })];
        _eventos_decorators = [(0, graphql_1.Field)(function () { return [EventoPartida]; }, { nullable: true })];
        _estatisticasJogadores_decorators = [(0, graphql_1.Field)(function () { return [EstatisticaJogador]; }, { nullable: true })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _dataHora_decorators, { kind: "field", name: "dataHora", static: false, private: false, access: { has: function (obj) { return "dataHora" in obj; }, get: function (obj) { return obj.dataHora; }, set: function (obj, value) { obj.dataHora = value; } }, metadata: _metadata }, _dataHora_initializers, _dataHora_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _golsCasa_decorators, { kind: "field", name: "golsCasa", static: false, private: false, access: { has: function (obj) { return "golsCasa" in obj; }, get: function (obj) { return obj.golsCasa; }, set: function (obj, value) { obj.golsCasa = value; } }, metadata: _metadata }, _golsCasa_initializers, _golsCasa_extraInitializers);
        __esDecorate(null, null, _golsVisitante_decorators, { kind: "field", name: "golsVisitante", static: false, private: false, access: { has: function (obj) { return "golsVisitante" in obj; }, get: function (obj) { return obj.golsVisitante; }, set: function (obj, value) { obj.golsVisitante = value; } }, metadata: _metadata }, _golsVisitante_initializers, _golsVisitante_extraInitializers);
        __esDecorate(null, null, _golsPenaltisCasa_decorators, { kind: "field", name: "golsPenaltisCasa", static: false, private: false, access: { has: function (obj) { return "golsPenaltisCasa" in obj; }, get: function (obj) { return obj.golsPenaltisCasa; }, set: function (obj, value) { obj.golsPenaltisCasa = value; } }, metadata: _metadata }, _golsPenaltisCasa_initializers, _golsPenaltisCasa_extraInitializers);
        __esDecorate(null, null, _golsPenaltisVisitante_decorators, { kind: "field", name: "golsPenaltisVisitante", static: false, private: false, access: { has: function (obj) { return "golsPenaltisVisitante" in obj; }, get: function (obj) { return obj.golsPenaltisVisitante; }, set: function (obj, value) { obj.golsPenaltisVisitante = value; } }, metadata: _metadata }, _golsPenaltisVisitante_initializers, _golsPenaltisVisitante_extraInitializers);
        __esDecorate(null, null, _competicao_decorators, { kind: "field", name: "competicao", static: false, private: false, access: { has: function (obj) { return "competicao" in obj; }, get: function (obj) { return obj.competicao; }, set: function (obj, value) { obj.competicao = value; } }, metadata: _metadata }, _competicao_initializers, _competicao_extraInitializers);
        __esDecorate(null, null, _equipeCasa_decorators, { kind: "field", name: "equipeCasa", static: false, private: false, access: { has: function (obj) { return "equipeCasa" in obj; }, get: function (obj) { return obj.equipeCasa; }, set: function (obj, value) { obj.equipeCasa = value; } }, metadata: _metadata }, _equipeCasa_initializers, _equipeCasa_extraInitializers);
        __esDecorate(null, null, _equipeVisitante_decorators, { kind: "field", name: "equipeVisitante", static: false, private: false, access: { has: function (obj) { return "equipeVisitante" in obj; }, get: function (obj) { return obj.equipeVisitante; }, set: function (obj, value) { obj.equipeVisitante = value; } }, metadata: _metadata }, _equipeVisitante_initializers, _equipeVisitante_extraInitializers);
        __esDecorate(null, null, _estadio_decorators, { kind: "field", name: "estadio", static: false, private: false, access: { has: function (obj) { return "estadio" in obj; }, get: function (obj) { return obj.estadio; }, set: function (obj, value) { obj.estadio = value; } }, metadata: _metadata }, _estadio_initializers, _estadio_extraInitializers);
        __esDecorate(null, null, _arbitro_decorators, { kind: "field", name: "arbitro", static: false, private: false, access: { has: function (obj) { return "arbitro" in obj; }, get: function (obj) { return obj.arbitro; }, set: function (obj, value) { obj.arbitro = value; } }, metadata: _metadata }, _arbitro_initializers, _arbitro_extraInitializers);
        __esDecorate(null, null, _treinadorCasa_decorators, { kind: "field", name: "treinadorCasa", static: false, private: false, access: { has: function (obj) { return "treinadorCasa" in obj; }, get: function (obj) { return obj.treinadorCasa; }, set: function (obj, value) { obj.treinadorCasa = value; } }, metadata: _metadata }, _treinadorCasa_initializers, _treinadorCasa_extraInitializers);
        __esDecorate(null, null, _treinadorVisitante_decorators, { kind: "field", name: "treinadorVisitante", static: false, private: false, access: { has: function (obj) { return "treinadorVisitante" in obj; }, get: function (obj) { return obj.treinadorVisitante; }, set: function (obj, value) { obj.treinadorVisitante = value; } }, metadata: _metadata }, _treinadorVisitante_initializers, _treinadorVisitante_extraInitializers);
        __esDecorate(null, null, _estatisticasEquipes_decorators, { kind: "field", name: "estatisticasEquipes", static: false, private: false, access: { has: function (obj) { return "estatisticasEquipes" in obj; }, get: function (obj) { return obj.estatisticasEquipes; }, set: function (obj, value) { obj.estatisticasEquipes = value; } }, metadata: _metadata }, _estatisticasEquipes_initializers, _estatisticasEquipes_extraInitializers);
        __esDecorate(null, null, _eventos_decorators, { kind: "field", name: "eventos", static: false, private: false, access: { has: function (obj) { return "eventos" in obj; }, get: function (obj) { return obj.eventos; }, set: function (obj, value) { obj.eventos = value; } }, metadata: _metadata }, _eventos_initializers, _eventos_extraInitializers);
        __esDecorate(null, null, _estatisticasJogadores_decorators, { kind: "field", name: "estatisticasJogadores", static: false, private: false, access: { has: function (obj) { return "estatisticasJogadores" in obj; }, get: function (obj) { return obj.estatisticasJogadores; }, set: function (obj, value) { obj.estatisticasJogadores = value; } }, metadata: _metadata }, _estatisticasJogadores_initializers, _estatisticasJogadores_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Partida = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Partida = _classThis;
}();
exports.Partida = Partida;
var EventoPartida = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _minuto_decorators;
    var _minuto_initializers = [];
    var _minuto_extraInitializers = [];
    var _minutoAcrescimo_decorators;
    var _minutoAcrescimo_initializers = [];
    var _minutoAcrescimo_extraInitializers = [];
    var _tipoEvento_decorators;
    var _tipoEvento_initializers = [];
    var _tipoEvento_extraInitializers = [];
    var _descricao_decorators;
    var _descricao_initializers = [];
    var _descricao_extraInitializers = [];
    var _equipeId_decorators;
    var _equipeId_initializers = [];
    var _equipeId_extraInitializers = [];
    var _jogador_decorators;
    var _jogador_initializers = [];
    var _jogador_extraInitializers = [];
    var EventoPartida = _classThis = /** @class */ (function () {
        function EventoPartida_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.minuto = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _minuto_initializers, void 0));
            this.minutoAcrescimo = (__runInitializers(this, _minuto_extraInitializers), __runInitializers(this, _minutoAcrescimo_initializers, void 0));
            this.tipoEvento = (__runInitializers(this, _minutoAcrescimo_extraInitializers), __runInitializers(this, _tipoEvento_initializers, void 0));
            this.descricao = (__runInitializers(this, _tipoEvento_extraInitializers), __runInitializers(this, _descricao_initializers, void 0));
            this.equipeId = (__runInitializers(this, _descricao_extraInitializers), __runInitializers(this, _equipeId_initializers, void 0));
            this.jogador = (__runInitializers(this, _equipeId_extraInitializers), __runInitializers(this, _jogador_initializers, void 0));
            __runInitializers(this, _jogador_extraInitializers);
        }
        return EventoPartida_1;
    }());
    __setFunctionName(_classThis, "EventoPartida");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _minuto_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _minutoAcrescimo_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _tipoEvento_decorators = [(0, graphql_1.Field)(function () { return String; })];
        _descricao_decorators = [(0, graphql_1.Field)(function () { return String; }, { nullable: true })];
        _equipeId_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _jogador_decorators = [(0, graphql_1.Field)(function () { return JogadorSimples; }, { nullable: true })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _minuto_decorators, { kind: "field", name: "minuto", static: false, private: false, access: { has: function (obj) { return "minuto" in obj; }, get: function (obj) { return obj.minuto; }, set: function (obj, value) { obj.minuto = value; } }, metadata: _metadata }, _minuto_initializers, _minuto_extraInitializers);
        __esDecorate(null, null, _minutoAcrescimo_decorators, { kind: "field", name: "minutoAcrescimo", static: false, private: false, access: { has: function (obj) { return "minutoAcrescimo" in obj; }, get: function (obj) { return obj.minutoAcrescimo; }, set: function (obj, value) { obj.minutoAcrescimo = value; } }, metadata: _metadata }, _minutoAcrescimo_initializers, _minutoAcrescimo_extraInitializers);
        __esDecorate(null, null, _tipoEvento_decorators, { kind: "field", name: "tipoEvento", static: false, private: false, access: { has: function (obj) { return "tipoEvento" in obj; }, get: function (obj) { return obj.tipoEvento; }, set: function (obj, value) { obj.tipoEvento = value; } }, metadata: _metadata }, _tipoEvento_initializers, _tipoEvento_extraInitializers);
        __esDecorate(null, null, _descricao_decorators, { kind: "field", name: "descricao", static: false, private: false, access: { has: function (obj) { return "descricao" in obj; }, get: function (obj) { return obj.descricao; }, set: function (obj, value) { obj.descricao = value; } }, metadata: _metadata }, _descricao_initializers, _descricao_extraInitializers);
        __esDecorate(null, null, _equipeId_decorators, { kind: "field", name: "equipeId", static: false, private: false, access: { has: function (obj) { return "equipeId" in obj; }, get: function (obj) { return obj.equipeId; }, set: function (obj, value) { obj.equipeId = value; } }, metadata: _metadata }, _equipeId_initializers, _equipeId_extraInitializers);
        __esDecorate(null, null, _jogador_decorators, { kind: "field", name: "jogador", static: false, private: false, access: { has: function (obj) { return "jogador" in obj; }, get: function (obj) { return obj.jogador; }, set: function (obj, value) { obj.jogador = value; } }, metadata: _metadata }, _jogador_initializers, _jogador_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        EventoPartida = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return EventoPartida = _classThis;
}();
exports.EventoPartida = EventoPartida;
var EstatisticaJogador = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _equipeId_decorators;
    var _equipeId_initializers = [];
    var _equipeId_extraInitializers = [];
    var _titular_decorators;
    var _titular_initializers = [];
    var _titular_extraInitializers = [];
    var _posicaoPartida_decorators;
    var _posicaoPartida_initializers = [];
    var _posicaoPartida_extraInitializers = [];
    var _numeroCamisa_decorators;
    var _numeroCamisa_initializers = [];
    var _numeroCamisa_extraInitializers = [];
    var _notaDesempenho_decorators;
    var _notaDesempenho_initializers = [];
    var _notaDesempenho_extraInitializers = [];
    var _minutosJogados_decorators;
    var _minutosJogados_initializers = [];
    var _minutosJogados_extraInitializers = [];
    var _gols_decorators;
    var _gols_initializers = [];
    var _gols_extraInitializers = [];
    var _assistencias_decorators;
    var _assistencias_initializers = [];
    var _assistencias_extraInitializers = [];
    var _passesCompletos_decorators;
    var _passesCompletos_initializers = [];
    var _passesCompletos_extraInitializers = [];
    var _desarmes_decorators;
    var _desarmes_initializers = [];
    var _desarmes_extraInitializers = [];
    var _posicaoMediaX_decorators;
    var _posicaoMediaX_initializers = [];
    var _posicaoMediaX_extraInitializers = [];
    var _posicaoMediaY_decorators;
    var _posicaoMediaY_initializers = [];
    var _posicaoMediaY_extraInitializers = [];
    var _heatmapUrl_decorators;
    var _heatmapUrl_initializers = [];
    var _heatmapUrl_extraInitializers = [];
    var _cartoesAmarelos_decorators;
    var _cartoesAmarelos_initializers = [];
    var _cartoesAmarelos_extraInitializers = [];
    var _cartoesVermelhos_decorators;
    var _cartoesVermelhos_initializers = [];
    var _cartoesVermelhos_extraInitializers = [];
    var _jogador_decorators;
    var _jogador_initializers = [];
    var _jogador_extraInitializers = [];
    var _partida_decorators;
    var _partida_initializers = [];
    var _partida_extraInitializers = [];
    var EstatisticaJogador = _classThis = /** @class */ (function () {
        function EstatisticaJogador_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.equipeId = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _equipeId_initializers, void 0));
            this.titular = (__runInitializers(this, _equipeId_extraInitializers), __runInitializers(this, _titular_initializers, void 0));
            this.posicaoPartida = (__runInitializers(this, _titular_extraInitializers), __runInitializers(this, _posicaoPartida_initializers, void 0));
            this.numeroCamisa = (__runInitializers(this, _posicaoPartida_extraInitializers), __runInitializers(this, _numeroCamisa_initializers, void 0));
            // 🎯 CORRIGIDO: Modificado de Number para Float
            this.notaDesempenho = (__runInitializers(this, _numeroCamisa_extraInitializers), __runInitializers(this, _notaDesempenho_initializers, void 0));
            this.minutosJogados = (__runInitializers(this, _notaDesempenho_extraInitializers), __runInitializers(this, _minutosJogados_initializers, void 0));
            this.gols = (__runInitializers(this, _minutosJogados_extraInitializers), __runInitializers(this, _gols_initializers, void 0));
            this.assistencias = (__runInitializers(this, _gols_extraInitializers), __runInitializers(this, _assistencias_initializers, void 0));
            this.passesCompletos = (__runInitializers(this, _assistencias_extraInitializers), __runInitializers(this, _passesCompletos_initializers, void 0));
            this.desarmes = (__runInitializers(this, _passesCompletos_extraInitializers), __runInitializers(this, _desarmes_initializers, void 0));
            // 🎯 CORRIGIDO: Modificado de Number para Float
            this.posicaoMediaX = (__runInitializers(this, _desarmes_extraInitializers), __runInitializers(this, _posicaoMediaX_initializers, void 0));
            this.posicaoMediaY = (__runInitializers(this, _posicaoMediaX_extraInitializers), __runInitializers(this, _posicaoMediaY_initializers, void 0));
            this.heatmapUrl = (__runInitializers(this, _posicaoMediaY_extraInitializers), __runInitializers(this, _heatmapUrl_initializers, void 0));
            this.cartoesAmarelos = (__runInitializers(this, _heatmapUrl_extraInitializers), __runInitializers(this, _cartoesAmarelos_initializers, void 0));
            this.cartoesVermelhos = (__runInitializers(this, _cartoesAmarelos_extraInitializers), __runInitializers(this, _cartoesVermelhos_initializers, void 0));
            this.jogador = (__runInitializers(this, _cartoesVermelhos_extraInitializers), __runInitializers(this, _jogador_initializers, void 0));
            this.partida = (__runInitializers(this, _jogador_extraInitializers), __runInitializers(this, _partida_initializers, void 0));
            __runInitializers(this, _partida_extraInitializers);
        }
        return EstatisticaJogador_1;
    }());
    __setFunctionName(_classThis, "EstatisticaJogador");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _equipeId_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _titular_decorators = [(0, graphql_1.Field)(function () { return Boolean; })];
        _posicaoPartida_decorators = [(0, graphql_1.Field)(function () { return String; }, { nullable: true })];
        _numeroCamisa_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _notaDesempenho_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Float; }, { nullable: true })];
        _minutosJogados_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _gols_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _assistencias_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _passesCompletos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _desarmes_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _posicaoMediaX_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Float; }, { nullable: true })];
        _posicaoMediaY_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Float; }, { nullable: true })];
        _heatmapUrl_decorators = [(0, graphql_1.Field)(function () { return String; }, { nullable: true })];
        _cartoesAmarelos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _cartoesVermelhos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _jogador_decorators = [(0, graphql_1.Field)(function () { return JogadorSimples; })];
        _partida_decorators = [(0, graphql_1.Field)(function () { return Partida; }, { nullable: true })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _equipeId_decorators, { kind: "field", name: "equipeId", static: false, private: false, access: { has: function (obj) { return "equipeId" in obj; }, get: function (obj) { return obj.equipeId; }, set: function (obj, value) { obj.equipeId = value; } }, metadata: _metadata }, _equipeId_initializers, _equipeId_extraInitializers);
        __esDecorate(null, null, _titular_decorators, { kind: "field", name: "titular", static: false, private: false, access: { has: function (obj) { return "titular" in obj; }, get: function (obj) { return obj.titular; }, set: function (obj, value) { obj.titular = value; } }, metadata: _metadata }, _titular_initializers, _titular_extraInitializers);
        __esDecorate(null, null, _posicaoPartida_decorators, { kind: "field", name: "posicaoPartida", static: false, private: false, access: { has: function (obj) { return "posicaoPartida" in obj; }, get: function (obj) { return obj.posicaoPartida; }, set: function (obj, value) { obj.posicaoPartida = value; } }, metadata: _metadata }, _posicaoPartida_initializers, _posicaoPartida_extraInitializers);
        __esDecorate(null, null, _numeroCamisa_decorators, { kind: "field", name: "numeroCamisa", static: false, private: false, access: { has: function (obj) { return "numeroCamisa" in obj; }, get: function (obj) { return obj.numeroCamisa; }, set: function (obj, value) { obj.numeroCamisa = value; } }, metadata: _metadata }, _numeroCamisa_initializers, _numeroCamisa_extraInitializers);
        __esDecorate(null, null, _notaDesempenho_decorators, { kind: "field", name: "notaDesempenho", static: false, private: false, access: { has: function (obj) { return "notaDesempenho" in obj; }, get: function (obj) { return obj.notaDesempenho; }, set: function (obj, value) { obj.notaDesempenho = value; } }, metadata: _metadata }, _notaDesempenho_initializers, _notaDesempenho_extraInitializers);
        __esDecorate(null, null, _minutosJogados_decorators, { kind: "field", name: "minutosJogados", static: false, private: false, access: { has: function (obj) { return "minutosJogados" in obj; }, get: function (obj) { return obj.minutosJogados; }, set: function (obj, value) { obj.minutosJogados = value; } }, metadata: _metadata }, _minutosJogados_initializers, _minutosJogados_extraInitializers);
        __esDecorate(null, null, _gols_decorators, { kind: "field", name: "gols", static: false, private: false, access: { has: function (obj) { return "gols" in obj; }, get: function (obj) { return obj.gols; }, set: function (obj, value) { obj.gols = value; } }, metadata: _metadata }, _gols_initializers, _gols_extraInitializers);
        __esDecorate(null, null, _assistencias_decorators, { kind: "field", name: "assistencias", static: false, private: false, access: { has: function (obj) { return "assistencias" in obj; }, get: function (obj) { return obj.assistencias; }, set: function (obj, value) { obj.assistencias = value; } }, metadata: _metadata }, _assistencias_initializers, _assistencias_extraInitializers);
        __esDecorate(null, null, _passesCompletos_decorators, { kind: "field", name: "passesCompletos", static: false, private: false, access: { has: function (obj) { return "passesCompletos" in obj; }, get: function (obj) { return obj.passesCompletos; }, set: function (obj, value) { obj.passesCompletos = value; } }, metadata: _metadata }, _passesCompletos_initializers, _passesCompletos_extraInitializers);
        __esDecorate(null, null, _desarmes_decorators, { kind: "field", name: "desarmes", static: false, private: false, access: { has: function (obj) { return "desarmes" in obj; }, get: function (obj) { return obj.desarmes; }, set: function (obj, value) { obj.desarmes = value; } }, metadata: _metadata }, _desarmes_initializers, _desarmes_extraInitializers);
        __esDecorate(null, null, _posicaoMediaX_decorators, { kind: "field", name: "posicaoMediaX", static: false, private: false, access: { has: function (obj) { return "posicaoMediaX" in obj; }, get: function (obj) { return obj.posicaoMediaX; }, set: function (obj, value) { obj.posicaoMediaX = value; } }, metadata: _metadata }, _posicaoMediaX_initializers, _posicaoMediaX_extraInitializers);
        __esDecorate(null, null, _posicaoMediaY_decorators, { kind: "field", name: "posicaoMediaY", static: false, private: false, access: { has: function (obj) { return "posicaoMediaY" in obj; }, get: function (obj) { return obj.posicaoMediaY; }, set: function (obj, value) { obj.posicaoMediaY = value; } }, metadata: _metadata }, _posicaoMediaY_initializers, _posicaoMediaY_extraInitializers);
        __esDecorate(null, null, _heatmapUrl_decorators, { kind: "field", name: "heatmapUrl", static: false, private: false, access: { has: function (obj) { return "heatmapUrl" in obj; }, get: function (obj) { return obj.heatmapUrl; }, set: function (obj, value) { obj.heatmapUrl = value; } }, metadata: _metadata }, _heatmapUrl_initializers, _heatmapUrl_extraInitializers);
        __esDecorate(null, null, _cartoesAmarelos_decorators, { kind: "field", name: "cartoesAmarelos", static: false, private: false, access: { has: function (obj) { return "cartoesAmarelos" in obj; }, get: function (obj) { return obj.cartoesAmarelos; }, set: function (obj, value) { obj.cartoesAmarelos = value; } }, metadata: _metadata }, _cartoesAmarelos_initializers, _cartoesAmarelos_extraInitializers);
        __esDecorate(null, null, _cartoesVermelhos_decorators, { kind: "field", name: "cartoesVermelhos", static: false, private: false, access: { has: function (obj) { return "cartoesVermelhos" in obj; }, get: function (obj) { return obj.cartoesVermelhos; }, set: function (obj, value) { obj.cartoesVermelhos = value; } }, metadata: _metadata }, _cartoesVermelhos_initializers, _cartoesVermelhos_extraInitializers);
        __esDecorate(null, null, _jogador_decorators, { kind: "field", name: "jogador", static: false, private: false, access: { has: function (obj) { return "jogador" in obj; }, get: function (obj) { return obj.jogador; }, set: function (obj, value) { obj.jogador = value; } }, metadata: _metadata }, _jogador_initializers, _jogador_extraInitializers);
        __esDecorate(null, null, _partida_decorators, { kind: "field", name: "partida", static: false, private: false, access: { has: function (obj) { return "partida" in obj; }, get: function (obj) { return obj.partida; }, set: function (obj, value) { obj.partida = value; } }, metadata: _metadata }, _partida_initializers, _partida_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        EstatisticaJogador = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return EstatisticaJogador = _classThis;
}();
exports.EstatisticaJogador = EstatisticaJogador;
var EstatisticaEquipe = function () {
    var _classDecorators = [(0, graphql_1.ObjectType)()];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _equipeId_decorators;
    var _equipeId_initializers = [];
    var _equipeId_extraInitializers = [];
    var _posseBola_decorators;
    var _posseBola_initializers = [];
    var _posseBola_extraInitializers = [];
    var _xG_decorators;
    var _xG_initializers = [];
    var _xG_extraInitializers = [];
    var _grandesChances_decorators;
    var _grandesChances_initializers = [];
    var _grandesChances_extraInitializers = [];
    var _chutes_decorators;
    var _chutes_initializers = [];
    var _chutes_extraInitializers = [];
    var _chutesGol_decorators;
    var _chutesGol_initializers = [];
    var _chutesGol_extraInitializers = [];
    var _chutesFora_decorators;
    var _chutesFora_initializers = [];
    var _chutesFora_extraInitializers = [];
    var _chutesNaTrave_decorators;
    var _chutesNaTrave_initializers = [];
    var _chutesNaTrave_extraInitializers = [];
    var _defesasGoleiro_decorators;
    var _defesasGoleiro_initializers = [];
    var _defesasGoleiro_extraInitializers = [];
    var _escanteios_decorators;
    var _escanteios_initializers = [];
    var _escanteios_extraInitializers = [];
    var _faltas_decorators;
    var _faltas_initializers = [];
    var _faltas_extraInitializers = [];
    var _impedimentos_decorators;
    var _impedimentos_initializers = [];
    var _impedimentos_extraInitializers = [];
    var _passesTentados_decorators;
    var _passesTentados_initializers = [];
    var _passesTentados_extraInitializers = [];
    var _passesCompletos_decorators;
    var _passesCompletos_initializers = [];
    var _passesCompletos_extraInitializers = [];
    var _cartoesAmarelos_decorators;
    var _cartoesAmarelos_initializers = [];
    var _cartoesAmarelos_extraInitializers = [];
    var _cartoesVermelhos_decorators;
    var _cartoesVermelhos_initializers = [];
    var _cartoesVermelhos_extraInitializers = [];
    var _formacao_decorators;
    var _formacao_initializers = [];
    var _formacao_extraInitializers = [];
    var EstatisticaEquipe = _classThis = /** @class */ (function () {
        function EstatisticaEquipe_1() {
            this.equipeId = __runInitializers(this, _equipeId_initializers, void 0);
            // 🎯 CORRIGIDO: Modificado de Number para Float
            this.posseBola = (__runInitializers(this, _equipeId_extraInitializers), __runInitializers(this, _posseBola_initializers, void 0));
            this.xG = (__runInitializers(this, _posseBola_extraInitializers), __runInitializers(this, _xG_initializers, void 0));
            this.grandesChances = (__runInitializers(this, _xG_extraInitializers), __runInitializers(this, _grandesChances_initializers, void 0));
            this.chutes = (__runInitializers(this, _grandesChances_extraInitializers), __runInitializers(this, _chutes_initializers, void 0));
            this.chutesGol = (__runInitializers(this, _chutes_extraInitializers), __runInitializers(this, _chutesGol_initializers, void 0));
            this.chutesFora = (__runInitializers(this, _chutesGol_extraInitializers), __runInitializers(this, _chutesFora_initializers, void 0));
            this.chutesNaTrave = (__runInitializers(this, _chutesFora_extraInitializers), __runInitializers(this, _chutesNaTrave_initializers, void 0));
            this.defesasGoleiro = (__runInitializers(this, _chutesNaTrave_extraInitializers), __runInitializers(this, _defesasGoleiro_initializers, void 0));
            this.escanteios = (__runInitializers(this, _defesasGoleiro_extraInitializers), __runInitializers(this, _escanteios_initializers, void 0));
            this.faltas = (__runInitializers(this, _escanteios_extraInitializers), __runInitializers(this, _faltas_initializers, void 0));
            this.impedimentos = (__runInitializers(this, _faltas_extraInitializers), __runInitializers(this, _impedimentos_initializers, void 0));
            this.passesTentados = (__runInitializers(this, _impedimentos_extraInitializers), __runInitializers(this, _passesTentados_initializers, void 0));
            this.passesCompletos = (__runInitializers(this, _passesTentados_extraInitializers), __runInitializers(this, _passesCompletos_initializers, void 0));
            this.cartoesAmarelos = (__runInitializers(this, _passesCompletos_extraInitializers), __runInitializers(this, _cartoesAmarelos_initializers, void 0));
            this.cartoesVermelhos = (__runInitializers(this, _cartoesAmarelos_extraInitializers), __runInitializers(this, _cartoesVermelhos_initializers, void 0));
            this.formacao = (__runInitializers(this, _cartoesVermelhos_extraInitializers), __runInitializers(this, _formacao_initializers, void 0));
            __runInitializers(this, _formacao_extraInitializers);
        }
        return EstatisticaEquipe_1;
    }());
    __setFunctionName(_classThis, "EstatisticaEquipe");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _equipeId_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; })];
        _posseBola_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Float; }, { nullable: true })];
        _xG_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Float; }, { nullable: true })];
        _grandesChances_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _chutes_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _chutesGol_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _chutesFora_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _chutesNaTrave_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _defesasGoleiro_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _escanteios_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _faltas_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _impedimentos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _passesTentados_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _passesCompletos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _cartoesAmarelos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _cartoesVermelhos_decorators = [(0, graphql_1.Field)(function () { return graphql_1.Int; }, { nullable: true })];
        _formacao_decorators = [(0, graphql_1.Field)(function () { return String; }, { nullable: true })];
        __esDecorate(null, null, _equipeId_decorators, { kind: "field", name: "equipeId", static: false, private: false, access: { has: function (obj) { return "equipeId" in obj; }, get: function (obj) { return obj.equipeId; }, set: function (obj, value) { obj.equipeId = value; } }, metadata: _metadata }, _equipeId_initializers, _equipeId_extraInitializers);
        __esDecorate(null, null, _posseBola_decorators, { kind: "field", name: "posseBola", static: false, private: false, access: { has: function (obj) { return "posseBola" in obj; }, get: function (obj) { return obj.posseBola; }, set: function (obj, value) { obj.posseBola = value; } }, metadata: _metadata }, _posseBola_initializers, _posseBola_extraInitializers);
        __esDecorate(null, null, _xG_decorators, { kind: "field", name: "xG", static: false, private: false, access: { has: function (obj) { return "xG" in obj; }, get: function (obj) { return obj.xG; }, set: function (obj, value) { obj.xG = value; } }, metadata: _metadata }, _xG_initializers, _xG_extraInitializers);
        __esDecorate(null, null, _grandesChances_decorators, { kind: "field", name: "grandesChances", static: false, private: false, access: { has: function (obj) { return "grandesChances" in obj; }, get: function (obj) { return obj.grandesChances; }, set: function (obj, value) { obj.grandesChances = value; } }, metadata: _metadata }, _grandesChances_initializers, _grandesChances_extraInitializers);
        __esDecorate(null, null, _chutes_decorators, { kind: "field", name: "chutes", static: false, private: false, access: { has: function (obj) { return "chutes" in obj; }, get: function (obj) { return obj.chutes; }, set: function (obj, value) { obj.chutes = value; } }, metadata: _metadata }, _chutes_initializers, _chutes_extraInitializers);
        __esDecorate(null, null, _chutesGol_decorators, { kind: "field", name: "chutesGol", static: false, private: false, access: { has: function (obj) { return "chutesGol" in obj; }, get: function (obj) { return obj.chutesGol; }, set: function (obj, value) { obj.chutesGol = value; } }, metadata: _metadata }, _chutesGol_initializers, _chutesGol_extraInitializers);
        __esDecorate(null, null, _chutesFora_decorators, { kind: "field", name: "chutesFora", static: false, private: false, access: { has: function (obj) { return "chutesFora" in obj; }, get: function (obj) { return obj.chutesFora; }, set: function (obj, value) { obj.chutesFora = value; } }, metadata: _metadata }, _chutesFora_initializers, _chutesFora_extraInitializers);
        __esDecorate(null, null, _chutesNaTrave_decorators, { kind: "field", name: "chutesNaTrave", static: false, private: false, access: { has: function (obj) { return "chutesNaTrave" in obj; }, get: function (obj) { return obj.chutesNaTrave; }, set: function (obj, value) { obj.chutesNaTrave = value; } }, metadata: _metadata }, _chutesNaTrave_initializers, _chutesNaTrave_extraInitializers);
        __esDecorate(null, null, _defesasGoleiro_decorators, { kind: "field", name: "defesasGoleiro", static: false, private: false, access: { has: function (obj) { return "defesasGoleiro" in obj; }, get: function (obj) { return obj.defesasGoleiro; }, set: function (obj, value) { obj.defesasGoleiro = value; } }, metadata: _metadata }, _defesasGoleiro_initializers, _defesasGoleiro_extraInitializers);
        __esDecorate(null, null, _escanteios_decorators, { kind: "field", name: "escanteios", static: false, private: false, access: { has: function (obj) { return "escanteios" in obj; }, get: function (obj) { return obj.escanteios; }, set: function (obj, value) { obj.escanteios = value; } }, metadata: _metadata }, _escanteios_initializers, _escanteios_extraInitializers);
        __esDecorate(null, null, _faltas_decorators, { kind: "field", name: "faltas", static: false, private: false, access: { has: function (obj) { return "faltas" in obj; }, get: function (obj) { return obj.faltas; }, set: function (obj, value) { obj.faltas = value; } }, metadata: _metadata }, _faltas_initializers, _faltas_extraInitializers);
        __esDecorate(null, null, _impedimentos_decorators, { kind: "field", name: "impedimentos", static: false, private: false, access: { has: function (obj) { return "impedimentos" in obj; }, get: function (obj) { return obj.impedimentos; }, set: function (obj, value) { obj.impedimentos = value; } }, metadata: _metadata }, _impedimentos_initializers, _impedimentos_extraInitializers);
        __esDecorate(null, null, _passesTentados_decorators, { kind: "field", name: "passesTentados", static: false, private: false, access: { has: function (obj) { return "passesTentados" in obj; }, get: function (obj) { return obj.passesTentados; }, set: function (obj, value) { obj.passesTentados = value; } }, metadata: _metadata }, _passesTentados_initializers, _passesTentados_extraInitializers);
        __esDecorate(null, null, _passesCompletos_decorators, { kind: "field", name: "passesCompletos", static: false, private: false, access: { has: function (obj) { return "passesCompletos" in obj; }, get: function (obj) { return obj.passesCompletos; }, set: function (obj, value) { obj.passesCompletos = value; } }, metadata: _metadata }, _passesCompletos_initializers, _passesCompletos_extraInitializers);
        __esDecorate(null, null, _cartoesAmarelos_decorators, { kind: "field", name: "cartoesAmarelos", static: false, private: false, access: { has: function (obj) { return "cartoesAmarelos" in obj; }, get: function (obj) { return obj.cartoesAmarelos; }, set: function (obj, value) { obj.cartoesAmarelos = value; } }, metadata: _metadata }, _cartoesAmarelos_initializers, _cartoesAmarelos_extraInitializers);
        __esDecorate(null, null, _cartoesVermelhos_decorators, { kind: "field", name: "cartoesVermelhos", static: false, private: false, access: { has: function (obj) { return "cartoesVermelhos" in obj; }, get: function (obj) { return obj.cartoesVermelhos; }, set: function (obj, value) { obj.cartoesVermelhos = value; } }, metadata: _metadata }, _cartoesVermelhos_initializers, _cartoesVermelhos_extraInitializers);
        __esDecorate(null, null, _formacao_decorators, { kind: "field", name: "formacao", static: false, private: false, access: { has: function (obj) { return "formacao" in obj; }, get: function (obj) { return obj.formacao; }, set: function (obj, value) { obj.formacao = value; } }, metadata: _metadata }, _formacao_initializers, _formacao_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        EstatisticaEquipe = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return EstatisticaEquipe = _classThis;
}();
exports.EstatisticaEquipe = EstatisticaEquipe;
